### ISSUE TITLE
Emmet LiveStyle: [client] Unterminated string at char 23717

### ISSUE THREAD

**Issue by enapupe** [emmetio/livestyle-sublime-old#10]
I'm having issue running livestyle on some local css files.
I thought it was related to char 23717 on my css file but my css file only goes to 17991. I tried to debug but couldn't understand this error message.

st2 v2.0.2 build 2221

{"url": "http://livestyle.emmet.io", "version": "2013.08.06.05.28.28", "description": "Live bi-directional CSS edit of new generation"}
{"url": "http://emmet.io", "version": "2013.08.06.05.28.52", "description": "Emmet (ex-Zen Coding) for Sublime Text"}

**Comment by sergeche** [comment]
It might happen in your browser CSS file. This error means LiveStyle can’t parse CSS, maybe it’s not valid.

**Comment by enapupe** [comment]
Cool, it was indeed something on a SVG inlined in my css file.Ty
Also, ty for the tool, very nice..
