### ISSUE TITLE
Please with this, log error

### ISSUE THREAD

**Issue by phangs** [emmetio/livestyle-sublime-old#104]
Please help me with this.  I am very new to CSS and would really love to do this journey with LiveStyle but every time I try to change anything in ST3 nothing is reflected in Chrome and vice versa.

Can the console log below help you assist me?  please assist me, I am very new to ST3 and CSS.  I can only go to the part where I need to map the CSS in the ST3 editor, that's the farthest I have reached. I was once successful in editing google search result but only once.  Please help.

startup, version: 3033 windows x32 channel: stable
executable: /C/Program Files/Sublime Text 3/sublime_text.exe
working dir: /C/Program Files/Sublime Text 3
packages path: /C/Users/HP-CNU941CTJ9/AppData/Roaming/Sublime Text 3/Packages
state path: /C/Users/HP-CNU941CTJ9/AppData/Roaming/Sublime Text 3/Local
hardware concurrency: 2
zip path: /C/Program Files/Sublime Text 3/Packages
zip path: /C/Users/HP-CNU941CTJ9/AppData/Roaming/Sublime Text 3/Installed Packages
resources scanned
found 3 files for base name Default.sublime-keymap
found 1 files for base name Default.sublime-mousemap
found 3 files for base name Main.sublime-menu
loading bindings
loading pointer bindings
found 1 files for base name Default.sublime-theme
theme loaded
app ready
pre session restore time: 0.397033
startup cache, total files: 149 cache hits: 149
startup time: 0.448033
first paint time: 0.449033
launching: /C/Program Files/Sublime Text 3/plugin_host.exe
loaded 837 snippets
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin LiveStyle.livestyle
reloading plugin Package Control.Package Control
plugins loaded
Package Control: Skipping automatic upgrade, last run at 2014-03-04 13:36:54, next run at 2014-03-04 14:36:54 or after
Emmet LiveStyle: No suitable client for diff
Emmet LiveStyle: No suitable client for diff
Writing file /D/Documents/Blue/AppXys/Pandora/css.css with encoding UTF-8 (atomic)
Emmet LiveStyle: No suitable client for diff
Emmet LiveStyle: No suitable client for diff
Emmet LiveStyle: No suitable client for diff
Emmet LiveStyle: No suitable client for diff
Emmet LiveStyle: No suitable client for diff
Emmet LiveStyle: No suitable client for diff
Emmet LiveStyle: No suitable client for diff
Emmet LiveStyle: No suitable client for diff
Emmet LiveStyle: No suitable client for diff
Emmet LiveStyle: No suitable client for diff
Emmet LiveStyle: No suitable client for diff
Emmet LiveStyle: No suitable client for diff
Emmet LiveStyle: No suitable client for diff
Emmet LiveStyle: No suitable client for diff
Emmet LiveStyle: No suitable client for diff
Emmet LiveStyle: No suitable client for diff
Emmet LiveStyle: No suitable client for diff
Emmet LiveStyle: No suitable client for diff
Emmet LiveStyle: No suitable client for diff
Emmet LiveStyle: No suitable client for diff
Emmet LiveStyle: No suitable client for diff
Emmet LiveStyle: No suitable client for diff
Emmet LiveStyle: No suitable client for diff
Emmet LiveStyle: No suitable client for diff
Emmet LiveStyle: No suitable client for diff
Emmet LiveStyle: No suitable client for diff
Emmet LiveStyle: No suitable client for diff
Emmet LiveStyle: No suitable client for diff
Emmet LiveStyle: No suitable client for diff
Emmet LiveStyle: No suitable client for diff
Emmet LiveStyle: No suitable client for diff
Emmet LiveStyle: No suitable client for diff
Emmet LiveStyle: No suitable client for diff
Emmet LiveStyle: No suitable client for diff
Emmet LiveStyle: No suitable client for diff
Emmet LiveStyle: No suitable client for diff
Emmet LiveStyle: No suitable client for diff
Emmet LiveStyle: No suitable client for diff
Emmet LiveStyle: No suitable client for diff
Emmet LiveStyle: No suitable client for diff
Emmet LiveStyle: No suitable client for diff
Emmet LiveStyle: No suitable client for diff
Emmet LiveStyle: No suitable client for diff
Emmet LiveStyle: No suitable client for diff
Emmet LiveStyle: No suitable client for diff
Emmet LiveStyle: No suitable client for diff

**Comment by sergeche** [comment]
You are using very outdated LiveStyle Chrome extension. Make sure it's version is at least 0.8.

Or you are trying to edit file other than CSS, for example, LESS or SCSS, which are not supported yet

**Comment by phangs** [comment]
thank you very much. before your reply, i re-installed the extension in chrome and st3, it works sometime and sometimes not, but at least most of the times it will, and i found out that I got some error on my css. i am very new to web design so please excuse my stupidity.

**Comment by us2h** [comment]
Chrome extension:
Version: 0.8.2.1230

Log when I make changes in css file:
Emmet LiveStyle: No suitable client for diff
Emmet LiveStyle: No suitable client for diff
Emmet LiveStyle: No suitable client for diff

**Comment by sergeche** [comment]
Either there’s no connected Chrome client (did you open DevTools?) or document’s syntax is not CSS

**Comment by us2h** [comment]
I think client connected:
https://www.dropbox.com/s/cnnv90qj83v08di/main.css__questionary_2014-11-05_11-15-12.png.png?dl=0

**Comment by sergeche** [comment]
Try to close and open DevTools again, or restart ST. 
The current version of LiveStyle is pretty abandoned because I’m working on new LiveStyle extension that has different architecture. It will be available soon for alpha-testing.

**Comment by us2h** [comment]
oh, restart is helped :) 
many thanks for your work. It's realy cool tool.
