### ISSUE TITLE
No active editor in chrome

### ISSUE THREAD

**Issue by faid** [emmetio/livestyle-sublime-old#115]
i have No avtive editor in my chrome Version 34.0.1847.131 m
Sublime text 2
my console :

startup, version: 2217 windows x32 channel: stable
executable: /C/Program Files/Sublime Text 2/sublime_text.exe
working dir: /C/Windows/system32
packages path: /C/Users/fidji/AppData/Roaming/Sublime Text 2/Packages
settings path: /C/Users/fidji/AppData/Roaming/Sublime Text 2/Settings
package /C/Users/fidji/AppData/Roaming/Sublime Text 2/Installed Packages/Package Control.sublime-package is newer than the installed version (/C/Users/fidji/AppData/Roaming/Sublime Text 2/Pristine Packages/Package Control.sublime-package), running PackageSetup
Py_GetProgramName(): sublime_text.exe
Py_GetExecPrefix(): C:\Program Files\Sublime Text 2
Py_GetProgramFullPath(): C:\Program Files\Sublime Text 2\sublime_text.exe
Py_GetPath(): C:\Program Files\Sublime Text 2\python26.zip;C:\Program Files\Sublime Text 2\DLLs;C:\Program Files\Sublime Text 2\lib;C:\Program Files\Sublime Text 2\lib\plat-win;C:\Program Files\Sublime Text 2\lib\lib-tk;C:\Program Files\Sublime Text 2
Py_GetPythonHome(): C:\Program Files\Sublime Text 2
PackageSetup returned: -1
catalogue loaded
found 4 files for base name Default.sublime-keymap
found 1 files for base name Default.sublime-mousemap
found 2 files for base name Main.sublime-menu
Reloading plugin C:\Users\fidji\AppData\Roaming\Sublime Text 2\Packages\CSS\css_completions.py
Reloading plugin C:\Users\fidji\AppData\Roaming\Sublime Text 2\Packages\Default\comment.py
Reloading plugin C:\Users\fidji\AppData\Roaming\Sublime Text 2\Packages\Default\copy_path.py
Reloading plugin C:\Users\fidji\AppData\Roaming\Sublime Text 2\Packages\Default\delete_word.py
Reloading plugin C:\Users\fidji\AppData\Roaming\Sublime Text 2\Packages\Default\detect_indentation.py
Reloading plugin C:\Users\fidji\AppData\Roaming\Sublime Text 2\Packages\Default\duplicate_line.py
Reloading plugin C:\Users\fidji\AppData\Roaming\Sublime Text 2\Packages\Default\echo.py
Reloading plugin C:\Users\fidji\AppData\Roaming\Sublime Text 2\Packages\Default\exec.py
Reloading plugin C:\Users\fidji\AppData\Roaming\Sublime Text 2\Packages\Default\fold.py
Reloading plugin C:\Users\fidji\AppData\Roaming\Sublime Text 2\Packages\Default\font.py
Reloading plugin C:\Users\fidji\AppData\Roaming\Sublime Text 2\Packages\Default\goto_line.py
Reloading plugin C:\Users\fidji\AppData\Roaming\Sublime Text 2\Packages\Default\indentation.py
Reloading plugin C:\Users\fidji\AppData\Roaming\Sublime Text 2\Packages\Default\kill_ring.py
Reloading plugin C:\Users\fidji\AppData\Roaming\Sublime Text 2\Packages\Default\mark.py
Reloading plugin C:\Users\fidji\AppData\Roaming\Sublime Text 2\Packages\Default\new_templates.py
Reloading plugin C:\Users\fidji\AppData\Roaming\Sublime Text 2\Packages\Default\open_file_settings.py
Reloading plugin C:\Users\fidji\AppData\Roaming\Sublime Text 2\Packages\Default\open_in_browser.py
Reloading plugin C:\Users\fidji\AppData\Roaming\Sublime Text 2\Packages\Default\paragraph.py
Reloading plugin C:\Users\fidji\AppData\Roaming\Sublime Text 2\Packages\Default\save_on_focus_lost.py
Reloading plugin C:\Users\fidji\AppData\Roaming\Sublime Text 2\Packages\Default\scroll.py
Reloading plugin C:\Users\fidji\AppData\Roaming\Sublime Text 2\Packages\Default\set_unsaved_view_name.py
Reloading plugin C:\Users\fidji\AppData\Roaming\Sublime Text 2\Packages\Default\side_bar.py
Reloading plugin C:\Users\fidji\AppData\Roaming\Sublime Text 2\Packages\Default\sort.py
Reloading plugin C:\Users\fidji\AppData\Roaming\Sublime Text 2\Packages\Default\swap_line.py
Reloading plugin C:\Users\fidji\AppData\Roaming\Sublime Text 2\Packages\Default\switch_file.py
Reloading plugin C:\Users\fidji\AppData\Roaming\Sublime Text 2\Packages\Default\transform.py
Reloading plugin C:\Users\fidji\AppData\Roaming\Sublime Text 2\Packages\Default\transpose.py
Reloading plugin C:\Users\fidji\AppData\Roaming\Sublime Text 2\Packages\Default\trim_trailing_white_space.py
Reloading plugin C:\Users\fidji\AppData\Roaming\Sublime Text 2\Packages\Diff\diff.py
Reloading plugin C:\Users\fidji\AppData\Roaming\Sublime Text 2\Packages\HTML\encode_html_entities.py
Reloading plugin C:\Users\fidji\AppData\Roaming\Sublime Text 2\Packages\HTML\html_completions.py
Reloading plugin C:\Users\fidji\AppData\Roaming\Sublime Text 2\Packages\Package Control\Package Control.py
plugin init time: 0.368571
loading bindings
loading pointer bindings
found 1 files for base name Default.sublime-theme
theme loaded
app ready
pre session restore time: 1.82483
startup cache, total files: 96 cache hits: 96
startup time: 1.89349 (package setup was run)
loaded 837 snippets
Package Control: No updated packages

please help me

**Comment by sergeche** [comment]
You should install LiveStyle for Sublime Text package first

**Comment by faid** [comment]
i install it :

found 1 files for base name Default.sublime-theme
theme loaded
app ready
pre session restore time: 0.539793
wrote startup cache, added files: 96 orphaned files: 0 total files: 96 cache hits: 0
startup time: 0.611142 (package setup was run)
loaded 837 snippets
Package Control: Skipping automatic upgrade, last run at 2014-05-10 18:00:18, next run at 2014-05-10 19:00:18 or after

> > > import urllib2,os,hashlib; h = '7183a2d3e96f11eeadd761d777e62404' + 'e330c659d4bb41d3bdf022e94cab3cd0'; pf = 'Package Control.sublime-package'; ipp = sublime.installed_packages_path(); os.makedirs( ipp ) if not os.path.exists(ipp) else None; urllib2.install_opener( urllib2.build_opener( urllib2.ProxyHandler()) ); by = urllib2.urlopen( 'http://sublime.wbond.net/' + pf.replace(' ', '%20')).read(); dh = hashlib.sha256(by).hexdigest(); open( os.path.join( ipp, pf), 'wb' ).write(by) if dh == h else None; print('Error validating download (got %s instead of %s), please try manual install' % (dh, h) if dh != h else 'Please restart Sublime Text to finish installation')
> > > Please restart Sublime Text to finish installation

i reboot ---> the same problém

**Comment by sergeche** [comment]
You didn’t installed LiveStyle package.
The code you pasted is Package Control installation
