### ISSUE TITLE
Stop working after a while - possibly by changing tabs

### ISSUE THREAD

**Issue by truedaz** [emmetio/livestyle-sublime-old#119]
Hello,

I love the idea of the extension. I got it up and running pretty quickly and it was fine for a bit. Now I really struggle to get it to work.

It shows in the dev tools panel and I select the file from the dropdown thats available in Sublime as I should but it does not always work.. I often select no style sheet, disable the extension and restart both Sublime and Chrome which im sure used to work but not any more.

I've found adding a new stylesheet can get it to work again.. but even if all the style sheets are selected to make changes to, either separate or the same CSS file... only the newly applied CSS file shows the amends in sublime. The new Css file I linked was for creating new CSS code with inspector-stylesheet.

I've also noticed switching tabs can break the link to sublime, even if I re-select the stylesheet it can still stop working.

I know its a lot of lague info.. i've been struggling to nail down a senario that either definatly breaks or fix's it.

Has anyone else had simmilar issues?

**Comment by truedaz** [comment]
Im getting somewhere with this.. I followed the debug instructions and am viewing the console log in Sublime.
It says:
Emmet LiveStyle: [client] Invalid CSS structure

so it seems there is something wrong with my site CSS?

Is there a validator out there? or someway I can find whats wrong with it?

Thanks!
D

**Comment by sergeche** [comment]
In most cases it means there’s a missing curly brace. Currently LiveStye doesn’t have validators but in next version will report problem spots in source code.

Try to use something line CSS linters, there must be online versions

**Comment by truedaz** [comment]
That is awesome! Top tip! Thanks! Is never heard of lint.

**Comment by truedaz** [comment]
Confirm fixed - I used the CSS lint checked at: http://csslint.net

removed a couple of stray curly brackets and bingo! - now works a charm again!
