### ISSUE TITLE
Pull changes from file into browser

### ISSUE THREAD

**Issue by JJCLane** [emmetio/livestyle-sublime-old#12]
If you assign a file with styles already there, these will not be brought into the browser. A feature could be added to mirror the changes from the whole file using the button between the file and the sublime text file?

It's a little hard to understand so here is how to reproduce it:
1. Open any web site and assign a new css file to it.
2. Write some styles to change the look of the page.
3. Refresh the page and these changes are no longer visible.

To get the changes back you have to go through each line and edit it so that it picks it up and injects it into the browser.

**Comment by sergeche** [comment]
I can create action in ST to push current file content to browser. Note that it will completely replace CSS file in browser, e.g. you can’t use this feature with different CSS files (for example, concatenated and minified in browser, formatted source module in editor).

But in your example, you should either save your changes in editor or do not refresh page in browser.

**Comment by JJCLane** [comment]
Yeah that makes sense. 

But in my example, if you save the file it won't have any effect as we're not updating the actual CSS used by the site. Not refreshing is an option, but if you accidentally hit a hyperlink, require a certain page state or require to navigate between pages the only option of applying the CSS is to go through and edit all the lines so they are pulled through.

**Comment by sergeche** [comment]
OK, I’ll implement this feature

**Comment by JJCLane** [comment]
Thankyou very much, this will be very useful.

**Comment by sergeche** [comment]
BTW, right now you can apply all recent changes by picking most recent entry in “Patch history” drop-down menu.

**Comment by JJCLane** [comment]
Yes, this seemed to be hit or miss though. Like it didn't create patches all the time and even if they were there, some if you made your way through clicking them they would change what they do.

**Comment by JJCLane** [comment]
Looks good, how do you use this feature?

**Comment by sergeche** [comment]
What do you mean? This feature is enabled by default and simply applies all unsaved changes on page reload

**Comment by JJCLane** [comment]
Ah right, I was trying it out earlier but couldn't seem to get it working, possibly don't have the newest update?

**Comment by sergeche** [comment]
You should have the most recent version of both Sublime Text and Chrome plugins.
