### ISSUE TITLE
Does Not work in Windows 7 x64 and With Sublime Text 3

### ISSUE THREAD

**Issue by msalehipro** [emmetio/livestyle-sublime-old#124]
Hi...
I use Google Chrome Version : 36.0.1985.125 m ( Latest Version ) and Sublime Text 3 Build 3021 on Windows 7 x64...
Before i install the latest version of Google Chrome, i installed LiveStyle Google Extension on it and it did work correctly !
but i don't know why it doesn't work no longer ...
Actually the issue is that i made some changes but i didn't see anything come alive and i should refresh the page to see my changes I've made!
i should notice that i can see the Sublime Text 3 on the LiveStyle Tab and LiveStyle can find my CSS file correctly... everything is OK but it doesn't work! :(
i tried to update Google Chrome but the issue does not fixed !
Please fix it as soon as...
Best Regard.

**Comment by sergeche** [comment]
https://github.com/emmetio/livestyle-sublime/blob/master/messages/install.txt

**Comment by msalehipro** [comment]
Yeah! Thanks so much Dear Sergey! the issue fixed!
Actually LiveStyle didn't have issue, that was a CSS Structure Error and I Guess the LiveStyle didn't can read my CSS file correctly...
I opened the console as you did said and i saw that the console tells me that : [Emmet] CSS Structure Error!
So i tried to validate my css using http://jigsaw.w3.org/css-validator/ and fixing my css errors...
Finally the LiveStyle did work correctly...
LiveStyle is very Sensitive to CSS Structure!
Thanks All LiveStyle Credits.
Mohammad.

**Comment by sergeche** [comment]
Yes, LiveStyle is very sensitive for CSS errors because it has to parse CSS it to detect structure diffs. In most cases non-working LiveStyle is caused by either CSS errors or proxies.

In next version I’ll try to improve error notifications.
