### ISSUE TITLE
css.valueSeparator

### ISSUE THREAD

**Issue by wm370857724** [emmetio/livestyle-sublime-old#125]
the user setting "css.valueSeparator": ":",can not work

{
  "preferences": {
    "css.valueSeparator": ":",
    "css.propertyEnd": "; "
  }
}

I had added this code to settings-user,but its not work,My editor is Sublime Text3

**Comment by sergeche** [comment]
This repo is for LiveStyle project, not Emmet.
Please add this issue here: https://github.com/sergeche/emmet-sublime
Also you should post full content of your `Emmet.sublime-settings` user file.

**Comment by sergeche** [comment]
And show what you receive and whet the expected result
