### ISSUE TITLE
SCSS color bug

### ISSUE THREAD

**Issue by iv-retriever** [emmetio/livestyle-sublime-old#139]
Hi, Im Korean Dev

Above all, proudly thx to make your really awesome livestyle 0.6 alpha.

I successed set SCSS <---> CSS and I tested. Almost good, But if I change 'color:red' to 'color:rgb(x, x, x)' css property in chrome devtool, It incorrectly change my .scss file in sublime like 'color:rgb'. So I cant change colors in chrome devtool.

How can I fix it.

Have a nice day :)

Thx!!

**Comment by sergeche** [comment]
Did you tried LiveStyle Alpha? http://livestyle.emmet.io/alpha/

**Comment by iv-retriever** [comment]
Ok, I succeeded the installation. But the problem happened.

**Comment by sergeche** [comment]
Did you removed old extension? Can you post a screenshot of both Chrome and ST with opened console?

**Comment by iv-retriever** [comment]
![2015-01-21 9 46 41](https://cloud.githubusercontent.com/assets/8910670/5829246/95287c6e-a152-11e4-8782-f91a5e0582e1.png)
![2015-01-21 9 47 09](https://cloud.githubusercontent.com/assets/8910670/5829247/95289a5a-a152-11e4-818d-c310f1b995c6.png)

I installed with your instruction. I think the procedure was perfect.

Chrome: color:black -> ST: color:black (nop)

Chrome: color:rgb(100, 100, 100) -> ST: color: rgb; (bug)

**Comment by iv-retriever** [comment]
![2015-01-21 9 53 56](https://cloud.githubusercontent.com/assets/8910670/5829295/7340a436-a153-11e4-9477-89b862503ddd.png)

This is my LS version.

**Comment by sergeche** [comment]
It’s a bug indeed. Please re-install Chrome extension, should be fixed

**Comment by iv-retriever** [comment]
OMG. It is solved!!!

Thanks :+1: 

Hmmm...

But I found other bug..

That is variable bug.

If I make var in .scss like this $a: 100px; and change the css in chrome devtool, So first change is good to work. But second, third, ... change make wrong value. This case is appeared only when I change value sequentially in chrome devtool.

ex)

$a: 100px;
body{
    margin-top:$a;
}
1. First change
Chrome: body{ margin-top:100px}   -->  body{ margin-top:50px}   /  ST: margin-top:$a - 50px; (good work)
1. Second change
   Chrome: body{ margin-top:50px}   -->  body{ margin-top:10px}   /  ST: margin-top:$a + 10px; (wrong calc,
   correct calc is $a - 90px)

I'm really sorry to bothering you.

**Comment by sergeche** [comment]
OK, thanks, I’ll check it out. 
You are not bothering me, I’d like to receive more reports like that :) 

Please report more issues at https://github.com/livestyle/issues/issues

**Comment by sergeche** [comment]
Thanks! Closing this issue for now
