### ISSUE TITLE
Chrome extension uninstalls every time the browser is closed.

### ISSUE THREAD

**Issue by bencoyour** [emmetio/livestyle-sublime-old#141]
Hello,

I was wondering if you had plans to put LiveStyle alpha in the Chrome web store soon?  Chrome thinks it's a malicious extension every time I open the browser and disables it.  Then I have to remove it and drag the extension back in to install, I then repeat this process every time I use Chrome.

I'm using the latest version of Chrome on Windows (Version 40.0.2214.111 m).  It works great when it's installed!

Do you know if there is any other way around this?  Thanks for all your hard work!

**Comment by sergeche** [comment]
Hello, try to enable Developer mode in Chrome Extensions pane

**Comment by bencoyour** [comment]
Thanks, that was simple!

**Comment by bencoyour** [comment]
Sorry to bug you about this again.  I realized that every time I shut down my computer and open Chrome it always disables livestyle.  I've resorted to leaving a copy of it on my desktop so every time I start Chrome I remove the old one and drag it over again for the new day.  It's tolerable, but it would be  ideal to not have to do that each time, it's such a solid tool (much improved over the beta version).  I did try the developer mode but it seems to be irrelevant when you're using the stable version of Chrome on Windows, it has to come from the marketplace or they turn it off.

Do you have any plans to submit it to the Google Apps Marketplace?  Is there a fee to do so?

By the way, I found the documentation of why it does this for Windows users here (3rd paragraph):
http://chrome.blogspot.com/2014/05/protecting-chrome-users-from-malicious.html

Thanks so much for your time and this awesome tool!
Ben

**Comment by sergeche** [comment]
Yes, I’m going to publish it in Chrome Webstore as soon as it will be available for public release. Right now I have to finish a few critical things

**Comment by bencoyour** [comment]
Awesome!  I'll close this issue and leave you alone.  Thanks!
