### ISSUE TITLE
Does not work special case (.htacces?)

### ISSUE THREAD

**Issue by mdillgen** [emmetio/livestyle-sublime-old#144]
Hi,

when i use LiveStyle with any public websites browser file it works perfectly, the editor updates apply quickly. 
But, at one special website, which is currently developed, it doesn’t work. I link the sites used "main.css" with the same "main.css" which is stored local on my computer and opened in Sublime Text 3.

Nothing happens, in both directions. I tried hard everything like cache clearing and so on, but i still can't figure out any solution. The only difference is, that the site is running in a password protected area. But i logged in and when it’s shown in the browser it shouldn’t be any problem, or is it? 
##

**Comment by sergeche** [comment]
No, there’s nothing about password-protection. Check ST log for errors. Also, try LiveStyle Alpha which displays more meaningful notification on extension icon and popup

**Comment by mdillgen** [comment]
Yeahhh! Problem solved. LiveStyle Alpha is the solution! Thanx!
