### ISSUE TITLE
Option to disable changes from browser reflecting on file

### ISSUE THREAD

**Issue by fritz-c** [emmetio/livestyle-sublime-old#147]
While editing, I like to do most of my work in the editor, and check things in Chrome. I'll occasionally tweak some values in Chrome's style tools to see how they are reflected in the browser, but I don't necessarily want those tweaks reflected in my files. Would it be possible to add an option to the sublime-settings file to disable the file-changing behavior?

**Comment by sergeche** [comment]
Try new alpha: http://livestyle.emmet.io/alpha/
