### ISSUE TITLE
livestyle emmet no longer working in Chrome Version 42.0.2311.152 dev-m

### ISSUE THREAD

**Issue by SpyrosKo** [emmetio/livestyle-sublime-old#149]
Livestyle emmet no longer working in Chrome Version 42.0.2311.152 dev-m
It was working the other day but when I tried it today, it no longer worked.

...
DPI scale: 1.25
startup, version: 3065 windows x64 channel: stable
executable: /C/Program Files/Sublime Text 3/sublime_text.exe
working dir: /C/Program Files/Sublime Text 3
packages path: /C/Users/Spiridon/AppData/Roaming/Sublime Text 3/Packages
state path: /C/Users/Spiridon/AppData/Roaming/Sublime Text 3/Local
hardware concurrency: 4
zip path: /C/Program Files/Sublime Text 3/Packages
zip path: /C/Users/Spiridon/AppData/Roaming/Sublime Text 3/Installed Packages
found 8 files for base name Default.sublime-keymap
found 2 files for base name Default.sublime-mousemap
found 10 files for base name Main.sublime-menu
loading bindings
loading pointer bindings
found 1 files for base name Default.sublime-theme
theme loaded
app ready
startup cache, total files: 231 cache hits: 231
pre session restore time: 0.202455
using gamma: 1.9 (err: 81.5966)
startup time: 0.233455
first paint time: 0.233455
launching: /C/Program Files/Sublime Text 3/plugin_host.exe
loaded 1540 snippets
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.02-bz2
reloading plugin BracketHighlighter.bh_core
reloading plugin BracketHighlighter.bh_logging
reloading plugin BracketHighlighter.bh_plugin
reloading plugin BracketHighlighter.bh_regions
reloading plugin BracketHighlighter.bh_remove
reloading plugin BracketHighlighter.bh_rules
reloading plugin BracketHighlighter.bh_search
reloading plugin BracketHighlighter.bh_swapping
reloading plugin BracketHighlighter.bh_wrapping
reloading plugin BracketHighlighter.ure
reloading plugin Emmet.emmet-plugin
reloading plugin HTML5.encode_html_entities
reloading plugin HTML5.html_completions
reloading plugin LiveStyle.livestyle
reloading plugin Package Control.bootstrap
reloading plugin Package Control.Package Control
reloading plugin SassBeautify.SassBeautify
reloading plugin SideBarEnhancements.SideBar
reloading plugin SideBarEnhancements.SideBarAPI
reloading plugin SideBarEnhancements.SideBarDefaultDisable
reloading plugin SublimeLinter-csslint.linter
SublimeLinter: csslint linter loaded 
reloading plugin SublimeLinter-html-tidy.linter
SublimeLinter: htmltidy linter loaded 
reloading plugin SublimeLinter-jshint.linter
SublimeLinter: jshint linter loaded 
reloading plugin HTML-CSS-JS Prettify.HTMLPrettify
reloading plugin SublimeCodeIntel.ordereddict
reloading plugin SublimeCodeIntel.SublimeCodeIntel
reloading plugin SublimeLinter.commands
reloading plugin SublimeLinter.sublimelinter
plugins loaded
SublimeLinter: debug mode: off 
SublimeLinter: WARNING: csslint deactivated, cannot locate 'csslint' 
Emmet LiveStyle: Prepare diff
Emmet LiveStyle: Cannot send message, client list empty
Emmet: No need to update PyV8
found 10 files for base name Main.sublime-menu
SublimeLinter: WARNING: jshint deactivated, cannot locate 'jshint' 
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 303, in on_activated
    callback.on_activated(v)
  File "C:\Users\Spiridon\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\sublimelinter.py", line 282, in on_activated
    self.check_syntax(view)
  File "C:\Users\Spiridon\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\sublimelinter.py", line 209, in check_syntax
    Linter.assign(view, reset=True)
  File "C:\Users\Spiridon\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\linter.py", line 724, in assign
    if not linter_class.disabled and linter_class.can_lint(syntax):
  File "./functools.py", line 251, in wrapper
  File "C:\Users\Spiridon\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\linter.py", line 1582, in can_lint
    status = 'WARNING: {} deactivated, cannot locate \'{}\''.format(cls.name, executable)
UnboundLocalError: local variable 'executable' referenced before assignment
Package Control: Skipping automatic upgrade, last run at 2015-05-17 13:50:08, next run at 2015-05-17 14:50:08 or after
Emmet LiveStyle: Prepare diff
Emmet LiveStyle: Cannot send message, client list empty
Emmet LiveStyle: client connected
Emmet LiveStyle: message received:
'{"action":"handshake","data":{"id":"chrome","supports":["css"]}}'
Emmet LiveStyle: Sending ws message '{"action": "id", "data": {"title": "Sublime Text 3", "files": ["C:\\Users\\Spiridon\\Desktop\\duplicating\\css\\mockpage1.css"], "icon": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABu0lEQVR42q2STWsTURhG3WvdCyq4CEVBAgYCM23JjEwy+cJC41gRdTIEGyELU7BNNMJQhUBBTUjSRdR
Emmet LiveStyle: Prepare diff
Emmet LiveStyle: Sending ws message '{"action": "updateFiles", "data": ["C:\\Users\\Spiridon\\Desktop\\duplicating\\css\\mockpage1.css"]}'
Emmet LiveStyle: Run diff
Emmet LiveStyle: Use connected "chrome" client for diff
Emmet LiveStyle: Sending ws message '{"action": "diff", "data": {"syntax": "css", "source2": "\* {\n    margin: 0;\n    padding: 0;\n}\n\n.nav {\n    width: 100%;\n    border: none;\n    background: rgb(159, 53, 56);\n    height: 50px;\n}\n\n\nli {\n    color: w;\n    padding: 20px;\n    float: left;\n}\n\na {\n  
WARNING:process:Could not import subprocess32 module, falling back to subprocess module
Emmet LiveStyle: message received:
'{"action":"diff","data":{"file":29,"success":true,"result":{"patches":[{"path":[["li",1]],"action":"update","properties":[{"name":"color","value":"w","index":0}],"removed":[]}],"source":"\* {\n    margin: 0;\n    padding: 0;\n}\n\n.nav {\n    width: 100%;\n    border: none;\n    background: 
Emmet LiveStyle: Run diff
Emmet LiveStyle: Run diff
Emmet LiveStyle: Run diff
Emmet LiveStyle: Run diff
Emmet LiveStyle: Received diff sources response: {'success': True, 'file': 29, 'result': {'source': '\* {\n    margin: 0;\n    padding: 0;\n}\n\n.nav {\n    width: 100%;\n    border: none;\n    background: rgb(159, 53, 56);\n    height: 50px;\n}\n\n\nli {\n    color: w;\n    padding: 20px;\n    float: left;\n}\n\na {\n    text-decoration: none;\n  
Emmet LiveStyle: Sending ws message '{"action": "update", "data": {"editorFile": "C:\\Users\\Spiridon\\Desktop\\duplicating\\css\\mockpage1.css", "patch": [{"action": "update", "properties": [{"index": 0, "value": "w", "name": "color"}], "removed": [], "path": [["li", 1]]}]}}'
Emmet LiveStyle: Diff performed in 2.7952s
Emmet LiveStyle: Use connected "chrome" client for diff
Emmet LiveStyle: Sending ws message '{"action": "diff", "data": {"syntax": "css", "source2": "\* {\n    margin: 0;\n    padding: 0;\n}\n\n.nav {\n    width: 100%;\n    border: none;\n    background: rgb(159, 53, 56);\n    height: 50px;\n}\n\n\nli {\n    color: white;\n    padding: 20px;\n    float: left;\n}\n\na {\n
Emmet LiveStyle: message received:
'{"action":"diff","data":{"file":29,"success":true,"result":{"patches":[{"path":[["li",1]],"action":"update","properties":[{"name":"color","value":"white","index":0}],"removed":[]}],"source":"\* {\n    margin: 0;\n    padding: 0;\n}\n\n.nav {\n    width: 100%;\n    border: none;\n    backgrou
Emmet LiveStyle: Received diff sources response: {'success': True, 'file': 29, 'result': {'source': '\* {\n    margin: 0;\n    padding: 0;\n}\n\n.nav {\n    width: 100%;\n    border: none;\n    background: rgb(159, 53, 56);\n    height: 50px;\n}\n\n\nli {\n    color: white;\n    padding: 20px;\n    float: left;\n}\n\na {\n    text-decoration: none;
Emmet LiveStyle: Sending ws message '{"action": "update", "data": {"editorFile": "C:\\Users\\Spiridon\\Desktop\\duplicating\\css\\mockpage1.css", "patch": [{"action": "update", "properties": [{"index": 0, "value": "white", "name": "color"}], "removed": [], "path": [["li", 1]]}]}}'
Emmet LiveStyle: Diff performed in 0.0320s
Writing file /C/Users/Spiridon/Desktop/duplicating/css/mockpage1.css with encoding UTF-8 (atomic)
Emmet LiveStyle: Prepare diff
Emmet LiveStyle: Sending ws message '{"action": "updateFiles", "data": ["C:\\Users\\Spiridon\\Desktop\\duplicating\\css\\mockpage1.css"]}'
WINDOW COMMAND ENABLED True
WINDOW COMMAND ENABLED True
WINDOW COMMAND ENABLED True
WINDOW COMMAND ENABLED True
WINDOW COMMAND ENABLED True
WINDOW COMMAND ENABLED False
Emmet LiveStyle: Prepare diff
Emmet LiveStyle: Sending ws message '{"action": "updateFiles", "data": ["C:\\Users\\Spiridon\\Desktop\\duplicating\\css\\mockpage1.css"]}'
Emmet LiveStyle: Prepare diff
Emmet LiveStyle: Sending ws message '{"action": "updateFiles", "data": ["C:\\Users\\Spiridon\\Desktop\\duplicating\\css\\mockpage1.css"]}'
Emmet LiveStyle: Prepare diff
Emmet LiveStyle: Sending ws message '{"action": "updateFiles", "data": ["C:\\Users\\Spiridon\\Desktop\\duplicating\\css\\mockpage1.css"]}'
...

**Comment by thinnling** [comment]
nevermind.  Strangely, it dies not work when I type in  <!DOCTYPE html> but works when <!doctype html> or <!DOCTYPE html> is used.
