### ISSUE TITLE
Unrecognized character '²' at char 25737

### ISSUE THREAD

**Issue by ehibes** [emmetio/livestyle-sublime-old#15]
When I modify css properties from browser, I get this error in SublimeText:

```
Emmet LiveStyle: [client] Unrecognized character '²' at char 25737
```

Browser or SublimeText modification doesn't refresh code or browser.
I installed all without any problem.

**Comment by sergeche** [comment]
Can you provide CSS snippet example where this character occurs?

**Comment by ehibes** [comment]
I can't reproduce this error. My css file is very long. But it always doesn't work. I created sample minimal html & css files to test console return and I get this : 

```
PyV8: Creating new thread
reloading plugin Package Control.Package Control
plugins loaded
Emmet LiveStyle: client connected
Emmet LiveStyle: You have the most recent PyV8 binary
Package Control: Skipping automatic upgrade, last run at 2013-08-06 18:16:33, next run at 2013-08-06 19:16:33 or after
Emmet LiveStyle: [client] No associated file found
Writing file /home/ibes/Mahaigaina/testemmet/style.css with encoding UTF-8 (atomic)
Emmet LiveStyle: [client] No associated file found
Emmet LiveStyle: [client] No associated file found
Emmet LiveStyle: [client] No associated file found
Emmet LiveStyle: [client] No associated file found
Emmet LiveStyle: [client] No associated file found
Emmet LiveStyle: [client] No associated file found
Emmet LiveStyle: [client] No associated file found
Emmet LiveStyle: [client] No associated file found
Emmet LiveStyle: [client] No associated file found
Writing file /home/ibes/Mahaigaina/testemmet/style.css with encoding UTF-8 (atomic)
```

I enabled LiveStyle on browser and associated file. I'm on ubuntu.

**Comment by sergeche** [comment]
Are you on stable Chrome or Canary?

**Comment by sergeche** [comment]
Are you on stable Chrome or Canary? I just figured out it doesn’t work in Canary

**Comment by ehibes** [comment]
Google Chrome stable Version 26.0.1410.63

**Comment by sergeche** [comment]
Try to update Chrome to most recent version (it’s 28)

**Comment by williw** [comment]
Emmet LiveStyle: [client] Unrecognized character '≈' at char 64915 I have the same Problem in Chrome 28 Lastest stable Version

**Comment by sergeche** [comment]
This error means your CSS is invalid. Check your CSS files for errors
