### ISSUE TITLE
No active editor in Chrome

### ISSUE THREAD

**Issue by VenomVendor** [emmetio/livestyle-sublime-old#17]
Chrome extension shows **No active editor**
- **After installing, below error occurs**
  [An error occurred while trying to upgrade LiveStyle](https://f.cloud.github.com/assets/1086927/922533/933cf86c-ff2d-11e2-847f-e0617e7820bc.jpg)
- **After restarting Sublime Text**
  [An error occurred while trying to finish the upgrade of LiveStyle](https://f.cloud.github.com/assets/1086927/922534/a473299e-ff2d-11e2-81ea-387b929bf01b.jpg)
- **After restarting the PC, the cycles continues.**

Tried with manual installation.
Win 8, 32 bit.

**Comment by VenomVendor** [comment]
Resetted ST.
Installed freshly.
Works fine now.
Unable to recreate the issue again.

**Comment by ghost** [comment]
I'm experiencing this issue with No active editor, running Chrome on a Win7 machine.  I've tried reinstalling everything from Sublime Text 3, to the Chrome Extension for Livestyle to Package Control and PyV8... nothing works.

You mentioned resetting ST... how did you do that?

**Comment by sergeche** [comment]
@losalgen post your ST console log here.
Also, if you’re using proxy, make sure it disabled or add exclusion to `localhost:54000` address

**Comment by ghost** [comment]
Here's the console output.  I even tried reinstalling everything and
installing it all according to instructions. The only issue I can see is
that it doesn't connect the extension in Chrome.

On Sat, Aug 10, 2013 at 5:43 PM, Sergey Chikuyonok <notifications@github.com

> wrote:
> 
> @losalgen https://github.com/losalgen post your ST console log here.
> Also, if you’re using proxy, make sure it disabled or add exclusion to
> localhost:54000 address
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/emmetio/livestyle-sublime/issues/17#issuecomment-22441910
> .
> 
> DPI scale: 1
> startup, version: 3047 windows x64 channel: stable
> executable: /C/Program Files/Sublime Text 3/sublime_text.exe
> working dir: /C/Program Files/Sublime Text 3
> packages path: /C/Users/UserName/AppData/Roaming/Sublime Text 3/Packages
> state path: /C/Users/UserName/AppData/Roaming/Sublime Text 3/Local
> hardware concurrency: 4
> zip path: /C/Program Files/Sublime Text 3/Packages
> zip path: /C/Users/UserName/AppData/Roaming/Sublime Text 3/Installed Packages
> found 3 files for base name Default.sublime-keymap
> found 1 files for base name Default.sublime-mousemap
> found 1 files for base name Main.sublime-menu
> generating syntax summary
> loading bindings
> loading pointer bindings
> found 1 files for base name Default.sublime-theme
> theme loaded
> app ready
> wrote startup cache, added files: 1 orphaned files: 10 total files: 145 cache hits: 144
> pre session restore time: 0.286192
> startup time: 0.316192
> first paint time: 0.319192
> launching: /C/Program Files/Sublime Text 3/plugin_host.exe
> loaded 837 snippets
> reloading plugin Default.block
> reloading plugin Default.comment
> reloading plugin Default.copy_path
> reloading plugin Default.delete_word
> reloading plugin Default.detect_indentation
> reloading plugin Default.duplicate_line
> reloading plugin Default.echo
> reloading plugin Default.exec
> reloading plugin Default.fold
> reloading plugin Default.font
> reloading plugin Default.goto_line
> reloading plugin Default.history_list
> reloading plugin Default.indentation
> reloading plugin Default.kill_ring
> reloading plugin Default.mark
> reloading plugin Default.new_templates
> reloading plugin Default.open_file_settings
> reloading plugin Default.open_in_browser
> reloading plugin Default.pane
> reloading plugin Default.paragraph
> reloading plugin Default.paste_from_history
> reloading plugin Default.save_on_focus_lost
> reloading plugin Default.scroll
> reloading plugin Default.set_unsaved_view_name
> reloading plugin Default.side_bar
> reloading plugin Default.sort
> reloading plugin Default.swap_line
> reloading plugin Default.switch_file
> reloading plugin Default.symbol
> reloading plugin Default.transform
> reloading plugin Default.transpose
> reloading plugin Default.trim_trailing_white_space
> reloading plugin CSS.css_completions
> reloading plugin Diff.diff
> reloading plugin HTML.encode_html_entities
> reloading plugin HTML.html_completions
> plugins loaded
> reloading plugin Package Control.Package Control
> found 2 files for base name Main.sublime-menu
> Package Control: No updated packages

DPI scale: 1
startup, version: 3047 windows x64 channel: stable
executable: /C/Program Files/Sublime Text 3/sublime_text.exe
working dir: /C/Program Files/Sublime Text 3
packages path: /C/Users/UserName/AppData/Roaming/Sublime Text 3/Packages
state path: /C/Users/UserName/AppData/Roaming/Sublime Text 3/Local
hardware concurrency: 4
zip path: /C/Program Files/Sublime Text 3/Packages
zip path: /C/Users/UserName/AppData/Roaming/Sublime Text 3/Installed Packages
found 3 files for base name Default.sublime-keymap
found 1 files for base name Default.sublime-mousemap
found 2 files for base name Main.sublime-menu
loading bindings
loading pointer bindings
found 1 files for base name Default.sublime-theme
theme loaded
app ready
startup cache, total files: 148 cache hits: 148
pre session restore time: 0.0854402
startup time: 0.12044
first paint time: 0.12144
launching: /C/Program Files/Sublime Text 3/plugin_host.exe
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
loaded 837 snippets
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin Package Control.Package Control
plugins loaded
Package Control: Skipping automatic upgrade, last run at 2013-08-10 17:25:01, next run at 2013-08-10 18:25:01 or after

**Comment by sergeche** [comment]
@losalgen from your log I can see that you have no installed LiveStyle plugin at all.

**Comment by ghost** [comment]
That's a little embarrassing, but I did it again, and installed it. Here's
the logs. Still no active editor.

**Comment by sergeche** [comment]
There’s still no LiveStyle plugin, only broken Package Control. Looks like you’ve double-installed Package Control.

You should see something like `Reloading plugin LiveStyle` in your console log.

**Comment by aanooj** [comment]
Facing the same issue with livestyle-sublime. try reinstalling everything but failed. 

Environment : Chrome : Version 28.0.1500.95 m, ST2, Win7

When checked with Fiddler, it shows the below error!

---

CONNECT localhost:54000 HTTP/1.1
Host: localhost:54000
Proxy-Connection: keep-alive

HTTP/1.1 502 Fiddler - Connection Failed
Date: Mon, 12 Aug 2013 07:19:21 GMT
Content-Type: text/html; charset=UTF-8
Connection: close
Timestamp: 12:49:21.163

[Fiddler] The socket connection to localhost failed. <br />ErrorCode: 10061. <br />No connection could be made because the target machine actively refused it 127.0.0.1:54000

**Comment by maxfarseer** [comment]
hi, i have same problem. Win7, ST2, Chrome 28.0.1500.95 m

in my log:
...
Reloading plugin C:\Users\maxfarseer\AppData\Roaming\Sublime Text 2\Packages\LiveStyle\livestyle.py
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 62, in reload_plugin
    m = imp.load_module(modulename, *m_info)
  File ".\livestyle.py", line 55, in <module>
    import lsutils.editor as eutils
  File ".\lsutils\editor.py", line 77
SyntaxError: Non-ASCII character '\xe2' in file .\lsutils\editor.py on line 77, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details
...
UPDATE:
work fine after this manipulation:
open ...\Sublime Text 2\Packages\LiveStyle\lsutils\editor.py
and added in the top: # coding=utf-8

**Comment by VenomVendor** [comment]
@aanooj You have to add exclusion to `localhost:54000`
 See Comment https://github.com/emmetio/livestyle-sublime/issues/17#issuecomment-22441910

**Comment by aanooj** [comment]
Started working after I added the #coding=utf-8 on the top.  However chrome crashes most of the time!

thanks @maxfarseer  for the tip.

**Comment by sergeche** [comment]
@aanooj can you describe at which time Chrome crashes? I have reports that constantly updating `*` selector may cause Chrome crash

**Comment by ghost** [comment]
I have the same issue. I use ubuntu 14.04 and just installed LiveStyle plugin in chrome. It shows 'no active editor' error. Also, the add file button doesn't respond.
![image](https://cloud.githubusercontent.com/assets/8874731/7221870/b351f102-e71b-11e4-8b86-b135a7e692b1.png)
