### ISSUE TITLE
No stylesheet found: 3256.2

### ISSUE THREAD

**Issue by juanfernandes** [emmetio/livestyle-sublime-old#19]
I'm getting the error: No stylesheet found: 3256.2: add of file here

I have installed LiveStyle on ST2, restarted it, updated Emmet too. 

The error happens when making changes in ST2. Not the other way round. 

OS: Ubuntu 13.04
Chrome: 28.0.1500.95

**Comment by sergeche** [comment]
Where do you get this error? In Chrome or Sublime Text?

**Comment by juanfernandes** [comment]
Sorry, in Chrome Console

**Comment by juanfernandes** [comment]
It could be how the environment is setup at work. I will try it at home tonight and see if its just me or something else.

**Comment by sergeche** [comment]
Can you attach a screenshot of DevTools with this error?

**Comment by juanfernandes** [comment]
![screenshot from 2013-08-07](https://f.cloud.github.com/assets/355046/924396/a8f3038e-ff66-11e2-80e4-5afcf3f9b33b.png)

I have to remove the URLs and blur out the site because its work.

**Comment by juanfernandes** [comment]
The only stylesheet that maps is base.css, the others, there is only base.css available to map to. Doesn't make sense to map base.css > main.css. I wasn't sure if it was related or not.

**Comment by sergeche** [comment]
It’s a Chrome notification meaning it can’t import CSS file. Most likely, you have broken `@import` statement. You should check your CSS and make sure it contains correct paths to imported stylesheets.

**Comment by juanfernandes** [comment]
I'm not using @import and the style sheets are loaded just fine. The error only shows when editing the style sheet with LiveStyle enabled. It didn't show before.

**Comment by juanfernandes** [comment]
Ok, using {$domainname_uri} - smarty templating - means it cannot map the CSS files. Have removed that and am linking to the css files as normal:

```
    <link rel="stylesheet" href="basement/css/base.css">
    <link rel="stylesheet" href="basement/css/main.css">
```

Still the same issue. If I disable LiveStyle, no more errors.

**Comment by sergeche** [comment]
Can you send me your CSS file to serge.che@gmail.com ? This error may happen only with invalid paths

**Comment by juanfernandes** [comment]
Sent.

**Comment by juanfernandes** [comment]
Ok, tested this at home, works perfectly. So the issue is most likely to do with the way the local domain is setup,
