### ISSUE TITLE
RuntimeError: Lock should be acquired before enter the context

### ISSUE THREAD

**Issue by daveMesmo** [emmetio/livestyle-sublime-old#24]
Hi,
This is not working for me on vista and the console shows:
...2\Packages\PyV8\win32\PyV8.py", line 168, in **enter**
    raise RuntimeError("Lock should be acquired before enter the context")
RuntimeError: Lock should be acquired before enter the context

Thank you,

**Comment by sergeche** [comment]
You should update Emmet and/or TernJS plugin to most recent version: http://livestyle.emmet.io/install/#sublime-text-extension

**Comment by daveMesmo** [comment]
thx, this is working great
