### ISSUE TITLE
emmet plugin don`t work after livestyle installed

### ISSUE THREAD

**Issue by ghost** [emmetio/livestyle-sublime-old#26]
After install livestyle, my emmet plugin doesn`t work . wonder why?

**Comment by sergeche** [comment]
Check out ST console for errors. If it says something about “entering context without proper locking” it means your Emmet plugin is outdated and you should update it to the most recent version

**Comment by owaisalhashimi** [comment]
Thanks for the great work. In ST3 Emmet also stopped working. I updated Emmet, all plugins. Emmet now working but LiveStyle still doesn't work, and the console is saying 
    `PyV8.JSError: JSError: <HandleScope::HandleScope> Entering the V8 API without proper locking in place ...`

**Comment by sergeche** [comment]
If you have TernJS plugin installed, you should update it as well. This error means you still has outdated Emmet or TernJS plugin

**Comment by owaisalhashimi** [comment]
Didn't have TernJS installed. Tried installing it, and it now freezes ST3, rendering it unusable. On Mountain Lion btw.

**Comment by sergeche** [comment]
Is it possible to receive ST console log?

**Comment by owaisalhashimi** [comment]
I will try to get you a log, when I can use ST3 again. It seems there might be a problem with PyV8, as I manually removed TernJS, PyV8, then re-installed Emmet from Package Control. When started up ST, as PyV8 was loading, ST froze again. I can't remember where I got PyV8 from originally, set it up a while ago.

**Comment by sergeche** [comment]
https://github.com/emmetio/pyv8-binaries#manual-installation

**Comment by owaisalhashimi** [comment]
Okay thanks got PyV8 again. 
Couldn't install LiveStyle from Package control. Installation problem doesn't seem to be restricted to Windows. Had to clone manually on Mountain Lion.
Just tested and it seems to be working fine now. Emmet also working.
Getting PyV8 again seems to have done it. Thanks for your time.

**Comment by sergeche** [comment]
LiveStyle should be listed in Package Control for ST3 now.
