### ISSUE TITLE
Not patching, throws a JS error

### ISSUE THREAD

**Issue by bzlies** [emmetio/livestyle-sublime-old#28]
Hey!

I'm getting the following error when editing my css:

Emmet LiveStyle: Error: JSError: [object Object](livestyle @ 13096 : 68)  -> =n.nextChar();i!==a;){if("\n"===i){if(t=n.nextChar(),"\"!==t)throw r("Untermi

Running Sublime Text 2 on Linux Mint 15

**Comment by francois-blanchard** [comment]
I'm getting this error : 

`Emmet LiveStyle: Error: JSError: <v8::Context::New()> Cannot find required extension`

This error occurs when i edit my css file.

config : Sublime Text 2 on Mac OS X 10.8

**Comment by sergeche** [comment]
@bzlies looks like your CSS is invalid, check it for errors
@francois-blanchard do you have Emmet or TernJS plugins installed? If so, make sure you have the most recent versions of this plugin.

**Comment by francois-blanchard** [comment]
I update Emmet and TernJS but I already have same error.

**Comment by sergeche** [comment]
Can you show me your full ST console log?

**Comment by francois-blanchard** [comment]
```
startup, version: 2221 osx x64 channel: stable
executable: /Applications/Sublime Text 2.app/Contents/MacOS/Sublime Text 2
working dir: /
packages path: /Users/Paco/Library/Application Support/Sublime Text 2/Packages
settings path: /Users/Paco/Library/Application Support/Sublime Text 2/Settings
PackageSetup not required
catalogue loaded
found 14 files for base name Default.sublime-keymap
found 1 files for base name Default.sublime-mousemap
found 13 files for base name Main.sublime-menu
Reloading plugin /Users/Paco/Library/Application Support/Sublime Text 2/Packages/AAAPackageDev/AAA.py
[AAAPackageDev] Added sublime_lib to sys.path.
Reloading plugin /Users/Paco/Library/Application Support/Sublime Text 2/Packages/AAAPackageDev/build_sys_dev.py
Reloading plugin /Users/Paco/Library/Application Support/Sublime Text 2/Packages/AAAPackageDev/commands_file_dev.py
Reloading plugin /Users/Paco/Library/Application Support/Sublime Text 2/Packages/AAAPackageDev/completions_dev.py
Reloading plugin /Users/Paco/Library/Application Support/Sublime Text 2/Packages/AAAPackageDev/package_dev.py
Reloading plugin /Users/Paco/Library/Application Support/Sublime Text 2/Packages/AAAPackageDev/settings_dev.py
Reloading plugin /Users/Paco/Library/Application Support/Sublime Text 2/Packages/AAAPackageDev/setup.py
Traceback (most recent call last):
  File "./sublime_plugin.py", line 62, in reload_plugin
  File "./setup.py", line 588, in <module>
    url='http://sublimetext.info',
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/distutils/core.py", line 106, in setup
    attrs['script_name'] = os.path.basename(sys.argv[0])
AttributeError: 'module' object has no attribute 'argv'
Reloading plugin /Users/Paco/Library/Application Support/Sublime Text 2/Packages/AAAPackageDev/snippet_dev.py
Reloading plugin /Users/Paco/Library/Application Support/Sublime Text 2/Packages/AAAPackageDev/sublime_inspect.py
Reloading plugin /Users/Paco/Library/Application Support/Sublime Text 2/Packages/AAAPackageDev/syntax_def_dev.py
Reloading plugin /Users/Paco/Library/Application Support/Sublime Text 2/Packages/Alignment/Alignment.py
Reloading plugin /Users/Paco/Library/Application Support/Sublime Text 2/Packages/BracketHighlighter/bh_core.py
Reloading plugin /Users/Paco/Library/Application Support/Sublime Text 2/Packages/BracketHighlighter/bh_plugin.py
Reloading plugin /Users/Paco/Library/Application Support/Sublime Text 2/Packages/BracketHighlighter/bh_remove.py
Reloading plugin /Users/Paco/Library/Application Support/Sublime Text 2/Packages/BracketHighlighter/bh_swapping.py
Reloading plugin /Users/Paco/Library/Application Support/Sublime Text 2/Packages/BracketHighlighter/bh_wrapping.py
Reloading plugin /Users/Paco/Library/Application Support/Sublime Text 2/Packages/BracketHighlighter/ure.py
Reloading plugin /Users/Paco/Library/Application Support/Sublime Text 2/Packages/CSS/css_completions.py
Reloading plugin /Users/Paco/Library/Application Support/Sublime Text 2/Packages/Default/comment.py
Reloading plugin /Users/Paco/Library/Application Support/Sublime Text 2/Packages/Default/copy_path.py
Reloading plugin /Users/Paco/Library/Application Support/Sublime Text 2/Packages/Default/delete_word.py
Reloading plugin /Users/Paco/Library/Application Support/Sublime Text 2/Packages/Default/detect_indentation.py
Reloading plugin /Users/Paco/Library/Application Support/Sublime Text 2/Packages/Default/duplicate_line.py
Reloading plugin /Users/Paco/Library/Application Support/Sublime Text 2/Packages/Default/echo.py
Reloading plugin /Users/Paco/Library/Application Support/Sublime Text 2/Packages/Default/exec.py
Reloading plugin /Users/Paco/Library/Application Support/Sublime Text 2/Packages/Default/fold.py
Reloading plugin /Users/Paco/Library/Application Support/Sublime Text 2/Packages/Default/font.py
Reloading plugin /Users/Paco/Library/Application Support/Sublime Text 2/Packages/Default/goto_line.py
Reloading plugin /Users/Paco/Library/Application Support/Sublime Text 2/Packages/Default/indentation.py
Reloading plugin /Users/Paco/Library/Application Support/Sublime Text 2/Packages/Default/kill_ring.py
Reloading plugin /Users/Paco/Library/Application Support/Sublime Text 2/Packages/Default/mark.py
Reloading plugin /Users/Paco/Library/Application Support/Sublime Text 2/Packages/Default/new_templates.py
Reloading plugin /Users/Paco/Library/Application Support/Sublime Text 2/Packages/Default/open_file_settings.py
Reloading plugin /Users/Paco/Library/Application Support/Sublime Text 2/Packages/Default/open_in_browser.py
Reloading plugin /Users/Paco/Library/Application Support/Sublime Text 2/Packages/Default/paragraph.py
Reloading plugin /Users/Paco/Library/Application Support/Sublime Text 2/Packages/Default/save_on_focus_lost.py
Reloading plugin /Users/Paco/Library/Application Support/Sublime Text 2/Packages/Default/scroll.py
Reloading plugin /Users/Paco/Library/Application Support/Sublime Text 2/Packages/Default/set_unsaved_view_name.py
Reloading plugin /Users/Paco/Library/Application Support/Sublime Text 2/Packages/Default/side_bar.py
Reloading plugin /Users/Paco/Library/Application Support/Sublime Text 2/Packages/Default/sort.py
Reloading plugin /Users/Paco/Library/Application Support/Sublime Text 2/Packages/Default/swap_line.py
Reloading plugin /Users/Paco/Library/Application Support/Sublime Text 2/Packages/Default/switch_file.py
Reloading plugin /Users/Paco/Library/Application Support/Sublime Text 2/Packages/Default/transform.py
Reloading plugin /Users/Paco/Library/Application Support/Sublime Text 2/Packages/Default/transpose.py
Reloading plugin /Users/Paco/Library/Application Support/Sublime Text 2/Packages/Default/trim_trailing_white_space.py
Reloading plugin /Users/Paco/Library/Application Support/Sublime Text 2/Packages/Diff/diff.py
Reloading plugin /Users/Paco/Library/Application Support/Sublime Text 2/Packages/Emmet/emmet-plugin.py
Emmet: No need to update PyV8
Reloading plugin /Users/Paco/Library/Application Support/Sublime Text 2/Packages/EncodingHelper/EncodingHelper.py
Reloading plugin /Users/Paco/Library/Application Support/Sublime Text 2/Packages/HTML/encode_html_entities.py
Reloading plugin /Users/Paco/Library/Application Support/Sublime Text 2/Packages/HTML/html_completions.py
Reloading plugin /Users/Paco/Library/Application Support/Sublime Text 2/Packages/LiveStyle/livestyle.py
Reloading plugin /Users/Paco/Library/Application Support/Sublime Text 2/Packages/Nettuts+ Fetch/Fetch.py
Reloading plugin /Users/Paco/Library/Application Support/Sublime Text 2/Packages/Package Control/Package Control.py
Reloading plugin /Users/Paco/Library/Application Support/Sublime Text 2/Packages/RubyTest/run_ruby_test.py
Reloading plugin /Users/Paco/Library/Application Support/Sublime Text 2/Packages/SCSS/scss_completions.py
Reloading plugin /Users/Paco/Library/Application Support/Sublime Text 2/Packages/Search WordPress Codex/WordPressCodex.py
Reloading plugin /Users/Paco/Library/Application Support/Sublime Text 2/Packages/SideBarEnhancements/SideBar.py
Reloading plugin /Users/Paco/Library/Application Support/Sublime Text 2/Packages/SideBarEnhancements/StatusBarFileSize.py
Reloading plugin /Users/Paco/Library/Application Support/Sublime Text 2/Packages/SideBarEnhancements/StatusBarModifiedTime.py
Reloading plugin /Users/Paco/Library/Application Support/Sublime Text 2/Packages/SplitScreen/split_screen.py
Reloading plugin /Users/Paco/Library/Application Support/Sublime Text 2/Packages/TernJS/tern.py
Reloading plugin /Users/Paco/Library/Application Support/Sublime Text 2/Packages/Xdebug/Xdebug.py
Reloading plugin /Users/Paco/Library/Application Support/Sublime Text 2/Packages/pyv8-osx/PyV8.py
plugin init time: 2.731
loading bindings
loading pointer bindings
found 1 files for base name Default.sublime-theme
Traceback (most recent call last):
  File "./livestyle.py", line 363, in start_plugin
    lsutils.diff.import_pyv8()
  File "./lsutils/diff.py", line 109, in import_pyv8
    js_ext = PyV8.JSExtension('livestyle', '\n'.join([js_emmet, js_livestyle]))
Boost.Python.ArgumentError: Python argument types in
    JSExtension.__init__(JSExtension, str, unicode)
did not match C++ signature:
    __init__(_object*, std::string name, std::string source, boost::python::api::object callback=None, boost::python::list dependencies=[], bool register=True)
theme loaded
app ready
pre session restore time: 2.97842
using gamma: 2 (err: 6.9282)
startup cache, total files: 142 cache hits: 142
startup time: 3.16472 (package setup was not run)
TernJS: No need to update PyV8
Syncing project empty
Starting TernJS server for empty with 1 libs and 0 files
Emmet LiveStyle: client connected
loaded 1415 snippets
Package Control: Skipping automatic upgrade, last run at 2013-08-09 16:50:34, next run at 2013-08-09 17:50:34 or after
Emmet LiveStyle: Error: JSError: <v8::Context::New()> Cannot find required extension
Emmet LiveStyle: Error: JSError: <v8::Context::New()> Cannot find required extension
Emmet LiveStyle: Error: JSError: <v8::Context::New()> Cannot find required extension
```

**Comment by sergeche** [comment]
Try to quit ST, remove `/Users/Paco/Library/Application Support/Sublime Text 2/Packages/pyv8-osx/` and start ST again. Looks like you have outdated PyV8 and it was installed incorrectly so LiveStyle can’t update it

**Comment by francois-blanchard** [comment]
thx you @sergeche. It works !

**Comment by bundlking** [comment]
Can we reopen this issue? - console dump. Same Error. OSX 10.6.8, Sublime Text v2.0.2, Chrome Version 28.0.1500.95

startup, version: 2221 osx x64 channel: stable
executable: /Applications/Sublime Text 2.app/Contents/MacOS/Sublime Text 2
working dir: /
packages path: /Users/Jon/Library/Application Support/Sublime Text 2/Packages
settings path: /Users/Jon/Library/Application Support/Sublime Text 2/Settings
PackageSetup not required
catalogue loaded
found 5 files for base name Default.sublime-keymap
found 1 files for base name Default.sublime-mousemap
found 4 files for base name Main.sublime-menu
Reloading plugin /Users/Jon/Library/Application Support/Sublime Text 2/Packages/CSS/css_completions.py
Reloading plugin /Users/Jon/Library/Application Support/Sublime Text 2/Packages/Default/comment.py
Reloading plugin /Users/Jon/Library/Application Support/Sublime Text 2/Packages/Default/copy_path.py
Reloading plugin /Users/Jon/Library/Application Support/Sublime Text 2/Packages/Default/delete_word.py
Reloading plugin /Users/Jon/Library/Application Support/Sublime Text 2/Packages/Default/detect_indentation.py
Reloading plugin /Users/Jon/Library/Application Support/Sublime Text 2/Packages/Default/duplicate_line.py
Reloading plugin /Users/Jon/Library/Application Support/Sublime Text 2/Packages/Default/echo.py
Reloading plugin /Users/Jon/Library/Application Support/Sublime Text 2/Packages/Default/exec.py
Reloading plugin /Users/Jon/Library/Application Support/Sublime Text 2/Packages/Default/fold.py
Reloading plugin /Users/Jon/Library/Application Support/Sublime Text 2/Packages/Default/font.py
Reloading plugin /Users/Jon/Library/Application Support/Sublime Text 2/Packages/Default/goto_line.py
Reloading plugin /Users/Jon/Library/Application Support/Sublime Text 2/Packages/Default/indentation.py
Reloading plugin /Users/Jon/Library/Application Support/Sublime Text 2/Packages/Default/kill_ring.py
Reloading plugin /Users/Jon/Library/Application Support/Sublime Text 2/Packages/Default/mark.py
Reloading plugin /Users/Jon/Library/Application Support/Sublime Text 2/Packages/Default/new_templates.py
Reloading plugin /Users/Jon/Library/Application Support/Sublime Text 2/Packages/Default/open_file_settings.py
Reloading plugin /Users/Jon/Library/Application Support/Sublime Text 2/Packages/Default/open_in_browser.py
Reloading plugin /Users/Jon/Library/Application Support/Sublime Text 2/Packages/Default/paragraph.py
Reloading plugin /Users/Jon/Library/Application Support/Sublime Text 2/Packages/Default/save_on_focus_lost.py
Reloading plugin /Users/Jon/Library/Application Support/Sublime Text 2/Packages/Default/scroll.py
Reloading plugin /Users/Jon/Library/Application Support/Sublime Text 2/Packages/Default/set_unsaved_view_name.py
Reloading plugin /Users/Jon/Library/Application Support/Sublime Text 2/Packages/Default/side_bar.py
Reloading plugin /Users/Jon/Library/Application Support/Sublime Text 2/Packages/Default/sort.py
Reloading plugin /Users/Jon/Library/Application Support/Sublime Text 2/Packages/Default/swap_line.py
Reloading plugin /Users/Jon/Library/Application Support/Sublime Text 2/Packages/Default/switch_file.py
Reloading plugin /Users/Jon/Library/Application Support/Sublime Text 2/Packages/Default/transform.py
Reloading plugin /Users/Jon/Library/Application Support/Sublime Text 2/Packages/Default/transpose.py
Reloading plugin /Users/Jon/Library/Application Support/Sublime Text 2/Packages/Default/trim_trailing_white_space.py
Reloading plugin /Users/Jon/Library/Application Support/Sublime Text 2/Packages/Diff/diff.py
Reloading plugin /Users/Jon/Library/Application Support/Sublime Text 2/Packages/Emmet/emmet-plugin.py
PyV8: Creating new thread
Emmet: Creating thread
Emmet: Loading https://api.github.com/repos/emmetio/pyv8-binaries/contents
Reloading plugin /Users/Jon/Library/Application Support/Sublime Text 2/Packages/HTML/encode_html_entities.py
Reloading plugin /Users/Jon/Library/Application Support/Sublime Text 2/Packages/HTML/html_completions.py
Reloading plugin /Users/Jon/Library/Application Support/Sublime Text 2/Packages/LiveStyle/livestyle.py
PyV8: Reusing thread
Reloading plugin /Users/Jon/Library/Application Support/Sublime Text 2/Packages/Package Control/Package Control.py
plugin init time: 0.381679
loading bindings
loading pointer bindings
found 1 files for base name Default.sublime-theme
theme loaded
app ready
pre session restore time: 0.553678
using gamma: 2 (err: 4.79583)
startup cache, total files: 102 cache hits: 102
startup time: 0.655741 (package setup was not run)
Emmet LiveStyle: Failed to import: No module named PyV8
Emmet LiveStyle: client connected
loaded 837 snippets
Emmet: Loading PyV8 binary from https://raw.github.com/emmetio/pyv8-binaries/master/pyv8-mac106.zip
Package Control: Skipping automatic upgrade, last run at 2013-08-11 22:12:14, next run at 2013-08-11 23:12:14 or after
Emmet LiveStyle: Failed to import: No module named PyV8
Emmet LiveStyle: Failed to import: No module named PyV8
Emmet LiveStyle: client disconnected
Emmet LiveStyle: client connected
Traceback (most recent call last):
  File "./sublime_plugin.py", line 195, in on_modified
  File "./sublime_plugin.py", line 154, in run_timed_function
  File "./sublime_plugin.py", line 194, in <lambda>
  File "./livestyle.py", line 230, in on_modified
    lsutils.diff.diff(view.buffer_id(), send_patches)
  File "./lsutils/diff.py", line 137, in diff
    if not import_pyv8():
  File "./lsutils/diff.py", line 109, in import_pyv8
    js_ext = PyV8.JSExtension('livestyle', '\n'.join([js_emmet, js_livestyle]))
Boost.Python.ArgumentError: Python argument types in
    JSExtension.**init**(JSExtension, str, unicode)
did not match C++ signature:
    **init**(_object*, std::string name, std::string source, boost::python::api::object callback=None, boost::python::list dependencies=[], bool register=True)
Emmet LiveStyle: Error: JSError: v8::Context::New() Cannot find required extension
Emmet LiveStyle: Error: JSError: v8::Context::New() Cannot find required extension
Emmet LiveStyle: Error: JSError: v8::Context::New() Cannot find required extension
Emmet LiveStyle: Error: JSError: v8::Context::New() Cannot find required extension
Emmet LiveStyle: Error: JSError: v8::Context::New() Cannot find required extension
Emmet LiveStyle: Error: JSError: v8::Context::New() Cannot find required extension
Emmet LiveStyle: Error: JSError: v8::Context::New() Cannot find required extension
Emmet LiveStyle: Error: JSError: v8::Context::New() Cannot find required extension
Emmet LiveStyle: Error: JSError: v8::Context::New() Cannot find required extension
Emmet LiveStyle: Error: JSError: v8::Context::New() Cannot find required extension
Emmet LiveStyle: Error: JSError: v8::Context::New() Cannot find required extension
Emmet LiveStyle: Error: JSError: v8::Context::New() Cannot find required extension
Emmet LiveStyle: Error: JSError: v8::Context::New() Cannot find required extension
Emmet LiveStyle: Error: JSError: v8::Context::New() Cannot find required extension
Emmet LiveStyle: Error: JSError: v8::Context::New() Cannot find required extension
Emmet LiveStyle: Error: JSError: v8::Context::New() Cannot find required extension
Emmet LiveStyle: Error: JSError: v8::Context::New() Cannot find required extension
Writing file /Library/WebServer/Documents/tipsta_v2/assets/css/tipstanew.css with encoding UTF-8

**Comment by sergeche** [comment]
@bundlking OSX 10.6 is not supported, sorry
