### ISSUE TITLE
Livestyle not loading in ST2

### ISSUE THREAD

**Issue by kalenjohnson** [emmetio/livestyle-sublime-old#3]
Hey there,

Thanks for the tweet Emmetio, good customer service on a free app ;)

Here's my console log after starting ST2:

<pre>
startup, version: 2221 linux x64 channel: stable
executable: /opt/sublime_text_2/sublime_text
working dir: /home/kalen
packages path: /home/kalen/.config/sublime-text-2/Packages
settings path: /home/kalen/.config/sublime-text-2/Settings
PackageSetup not required
Py_GetProgramName(): sublime_text
Py_GetExecPrefix(): .
Py_GetProgramFullPath(): 
Py_GetPath(): ./lib/python26.zip:./lib/python2.6/:./lib/python2.6/plat-linux2:./lib/python2.6/lib-tk:./lib/python2.6/lib-old:./lib/python2.6/lib-dynload
Py_GetPythonHome(): .
catalogue loaded
found 6 files for base name Default.sublime-keymap
found 1 files for base name Default.sublime-mousemap
found 6 files for base name Main.sublime-menu
Reloading plugin /home/kalen/.config/sublime-text-2/Packages/CSS/css_completions.py
Reloading plugin /home/kalen/.config/sublime-text-2/Packages/Default/comment.py
Reloading plugin /home/kalen/.config/sublime-text-2/Packages/Default/copy_path.py
Reloading plugin /home/kalen/.config/sublime-text-2/Packages/Default/delete_word.py
Reloading plugin /home/kalen/.config/sublime-text-2/Packages/Default/detect_indentation.py
Reloading plugin /home/kalen/.config/sublime-text-2/Packages/Default/duplicate_line.py
Reloading plugin /home/kalen/.config/sublime-text-2/Packages/Default/echo.py
Reloading plugin /home/kalen/.config/sublime-text-2/Packages/Default/exec.py
Reloading plugin /home/kalen/.config/sublime-text-2/Packages/Default/fold.py
Reloading plugin /home/kalen/.config/sublime-text-2/Packages/Default/font.py
Reloading plugin /home/kalen/.config/sublime-text-2/Packages/Default/goto_line.py
Reloading plugin /home/kalen/.config/sublime-text-2/Packages/Default/indentation.py
Reloading plugin /home/kalen/.config/sublime-text-2/Packages/Default/kill_ring.py
Reloading plugin /home/kalen/.config/sublime-text-2/Packages/Default/mark.py
Reloading plugin /home/kalen/.config/sublime-text-2/Packages/Default/new_templates.py
Reloading plugin /home/kalen/.config/sublime-text-2/Packages/Default/open_file_settings.py
Reloading plugin /home/kalen/.config/sublime-text-2/Packages/Default/open_in_browser.py
Reloading plugin /home/kalen/.config/sublime-text-2/Packages/Default/paragraph.py
Reloading plugin /home/kalen/.config/sublime-text-2/Packages/Default/save_on_focus_lost.py
Reloading plugin /home/kalen/.config/sublime-text-2/Packages/Default/scroll.py
Reloading plugin /home/kalen/.config/sublime-text-2/Packages/Default/set_unsaved_view_name.py
Reloading plugin /home/kalen/.config/sublime-text-2/Packages/Default/side_bar.py
Reloading plugin /home/kalen/.config/sublime-text-2/Packages/Default/sort.py
Reloading plugin /home/kalen/.config/sublime-text-2/Packages/Default/swap_line.py
Reloading plugin /home/kalen/.config/sublime-text-2/Packages/Default/switch_file.py
Reloading plugin /home/kalen/.config/sublime-text-2/Packages/Default/transform.py
Reloading plugin /home/kalen/.config/sublime-text-2/Packages/Default/transpose.py
Reloading plugin /home/kalen/.config/sublime-text-2/Packages/Default/trim_trailing_white_space.py
Reloading plugin /home/kalen/.config/sublime-text-2/Packages/Diff/diff.py
Reloading plugin /home/kalen/.config/sublime-text-2/Packages/Emmet/emmet-plugin.py
Emmet: No need to update PyV8
Reloading plugin /home/kalen/.config/sublime-text-2/Packages/HTML/encode_html_entities.py
Reloading plugin /home/kalen/.config/sublime-text-2/Packages/HTML/html_completions.py
Reloading plugin /home/kalen/.config/sublime-text-2/Packages/JavaScript and jQuery API Completions/main.py
Reloading plugin /home/kalen/.config/sublime-text-2/Packages/LiveStyle/livestyle.py
Traceback (most recent call last):
  File "./sublime_plugin.py", line 62, in reload_plugin
  File "./livestyle.py", line 57, in <module>
    import lsutils.webkit_installer
  File "./lsutils/webkit_installer.py", line 4, in <module>
    import io
  File ".\io.py", line 63, in <module>
ImportError: No module named _fileio
Reloading plugin /home/kalen/.config/sublime-text-2/Packages/Package Control/Package Control.py
Reloading plugin /home/kalen/.config/sublime-text-2/Packages/SCSS/scss_completions.py
Reloading plugin /home/kalen/.config/sublime-text-2/Packages/Search WordPress Codex/WordPressCodex.py
plugin init time: 0.145446
loading bindings
loading pointer bindings
found 1 files for base name Default.sublime-theme
theme loaded
app ready
pre session restore time: 0.285978
using gamma: 1 (err: 0)
startup cache, total files: 112 cache hits: 112
startup time: 0.381081 (package setup was not run)
loaded 1731 snippets
Package Control: Skipping automatic upgrade, last run at 2013-08-05 11:39:50, next run at 2013-08-05 12:39:50 or after
</pre>

**Comment by sergeche** [comment]
I’ve just pushed update that might fix this issue. Please re-install this extension.

**Comment by kalenjohnson** [comment]
Hey, that fixed it! Thanks a lot
