### ISSUE TITLE
Doesn't work with chrome workflow

### ISSUE THREAD

**Issue by webuniverseio** [emmetio/livestyle-sublime-old#33]
If workflow (http://goo.gl/J9rL9d) is setup for current url - livescript doesn't work. Don't know if it is a bug or not. If I'll disable workflow then I wouldn't be able to edit javascript from browser. However this is not the end of the world, I can live with that :)

---

Update actually it is working, but doesn't show *.scss files. If workflow is off - livescript will show them.

Thanks

**Comment by sergeche** [comment]
SCSS is not currently supported: http://livestyle.emmet.io/about/#will-it-work-with-sassscssless

**Comment by webuniverseio** [comment]
I understand limitations which you have in current state of scss support. If you need testers, I would like to be one of them. Even for very raw beta :)

---

Update, just thought - would be good to have some sort of config setting for scss testing.
