### ISSUE TITLE
Why I can't find 'livestyle' in sublime text3's package control?

### ISSUE THREAD

**Issue by imsobear** [emmetio/livestyle-sublime-old#35]
Like the title:

When I input 'LiveStyle' in Package Control, there is nothing for i installed.

---

update:

It is only support for sublime text2!

**Comment by sergeche** [comment]
It supports ST3 too, but was mistakenly marked as ST2-only in Package Control. I’ve sent PR to fix this.

**Comment by imsobear** [comment]
yeah, I find it today, Thanks very much!

**Comment by caprica-Six** [comment]
same problem here - cannot see 'LiveStyle' in Package Control. I have the Package installed.
By the way, do i have to keep the old version ST2 to have ST3 running, or could it be a separate one?
Could you help Sergey.

Much appreciated
thank you

**Comment by caprica-Six** [comment]
& i suppose i don't have to install git for my win64, ST2 was wroking fine...?
thank you

**Comment by caprica-Six** [comment]
All good-all working after a good reboot. Have triple checked the steps & is working fine now.....
Great job, anyway - big thank you!
