### ISSUE TITLE
Can't install it on ST3 with W7 x64

### ISSUE THREAD

**Issue by montogeek** [emmetio/livestyle-sublime-old#36]
I installled Package Control from his website using the console, the Package Control works perfect, I can install another plugins without problems, but with LiveStyle, it just don't appear in the list, Why? I already have PyV8 installed, I had installed the Chrome extension, but nothing works, please, help me :)

**Comment by Alecfoy** [comment]
I have the same problem on Mac OSX 10.8 with ST V.3.0.5.2. I can see other packages from Emmet 
![skrmbillede 2013-08-10 kl 22 27 54](https://f.cloud.github.com/assets/5204732/943194/6ff79242-01fb-11e3-8b0c-7937c50e2f49.png) 
But not LiveStyle

**Comment by sergeche** [comment]
Try to search “LiveStyle”. Also, you should wait a bit until Package Control channel is updated, it has mistakenly marked LiveStyle as ST2-only plugin.

**Comment by Alecfoy** [comment]
Hi Sergeche
I tired, but no luck.

**Comment by sergeche** [comment]
Then you have to wait until Package Control is updated or simply clone this repo into Packages folder

**Comment by Alecfoy** [comment]
Thanks, cloning the repo to packages did the job.

**Comment by montogeek** [comment]
Meanwhile clone this repo to the Packages folder work https://github.com/emmetio/livestyle-sublime :)
