### ISSUE TITLE
Edit Local files LiveStyle

### ISSUE THREAD

**Issue by ushakovme** [emmetio/livestyle-sublime-old#37]
I liked you new coll feature, but it can't change local files. it can jsut change peges from the net

**Comment by sergeche** [comment]
Check “Allow access to local files” in Extensions page

**Comment by JacobBennett** [comment]
Hey Sergeche, I seem to be having the same problem and can't find the option you are referencing. Here is all I am seeing when I look at the Extensions page.

![image](https://f.cloud.github.com/assets/1517011/954936/776a8c3c-0421-11e3-9c41-cf4deea9dda2.png)
![image](https://f.cloud.github.com/assets/1517011/954938/8004aae4-0421-11e3-8159-f19a9edb1616.png)

**Comment by sergeche** [comment]
Can you open `background.html` page of LiveStyle extension and check if there are errors when you’re trying to edit local page?

**Comment by JacobBennett** [comment]
When I was editing my local file in DevTools I got this error
![image](https://f.cloud.github.com/assets/1517011/955671/741db56a-042e-11e3-857a-90083e1d8c5b.png)

Anything edited in Sublime was never reflected in the page either. LiveReload style that is. If I manually refreshed the page of course it would work.

Thanks for any help.

**Comment by sergeche** [comment]
It means your CSS is invalid. Check it for errors.

**Comment by JacobBennett** [comment]
All of my CSS is invalid or only the current one I'm editing. I'll check it out.

**Comment by sergeche** [comment]
The one you’re editing in browser

**Comment by JacobBennett** [comment]
Ran my CSS through CSSLint and came back with some warnings about headings but no errors. I have found however that my installation won't even edit live pages like Google or Facebook as in the demonstraton and reflect changes in ST2. Maybe I'll uninstall everything and start over later when I have more time.

Looks like an AWESOME TOOL, just wish I could get it to work :)

**Comment by sergeche** [comment]
Can you send me your CSS file?

**Comment by sergeche** [comment]
Just pushed update, it should provide better error reporting on CSS parsing errors.
PS: make sure your Chrome extension is updated too to at least 0.8.0.816 version. Otherwise package won’t work.
