### ISSUE TITLE
Adding new css rule in browser doesn't add in sublime text

### ISSUE THREAD

**Issue by bhanna** [emmetio/livestyle-sublime-old#38]
Using the "New Style Rule" tool in inspector does not add a new style in the .css file in sublime text.

http://cl.ly/image/0U2S3a100B0C

This means I need to put empty class rules in css and then move back to browser to edit their definition. Any plans to include add style rule (to bottom of document maybe?)

**Comment by sergeche** [comment]
The newly created rule is anonymous, e.g. it doesn’t has any selector so it can’t be added to the editor.

LiveStyle workflow assumes that you should create new rules (with selectors) in editor rather than in browser.

**Comment by sergeche** [comment]
Make sure you’ve associated `inspector` stylesheet in LiveStyle panel with required editor file
