### ISSUE TITLE
No active editor in Chrome

### ISSUE THREAD

**Issue by larstid** [emmetio/livestyle-sublime-old#40]
Chrome and Chrome Canary can't detect my ST 2 Editor when opened. Even after a clean fresh new installation of ST 2, still not working.

Sublime Text 2
2.0.2, Build 2221

Chrome 28.0.1500.95 m

**Comment by sergeche** [comment]
Post your ST console log here

**Comment by larstid** [comment]
There's nothing in the console log. No Error.

**Comment by larstid** [comment]
Maybe there's a conflict with another package.

That Packages i had installed:

CoffeScript
Local Historiy
PlainTasks
Prefixr
SFTP
SVN
SublimeLinter

**Comment by larstid** [comment]
All these Packages btw. are up to date.

**Comment by sergeche** [comment]
Can you just post full console log?

**Comment by larstid** [comment]
When i open up the console in ST2 there's nothing related to livestyle. How can i get the console log you want? In Chrome the console log also got no livestyle error.

**Comment by sergeche** [comment]
Just copy and paste full log, like so: https://github.com/emmetio/livestyle-sublime/issues/20#issuecomment-22310292

**Comment by larstid** [comment]
here it is:

startup, version: 2221 windows x64 channel: stable
executable: /E/Applications/Sublime Text 2/sublime_text.exe
working dir: /E/Applications/Sublime Text 2
packages path: /C/Users/lt/AppData/Roaming/Sublime Text 2/Packages
settings path: /C/Users/lt/AppData/Roaming/Sublime Text 2/Settings
PackageSetup not required
Py_GetProgramName(): sublime_text.exe
Py_GetExecPrefix(): E:\Applications\Sublime Text 2
Py_GetProgramFullPath(): E:\Applications\Sublime Text 2\sublime_text.exe
Py_GetPath(): E:\Applications\Sublime Text 2\python26.zip;E:\Applications\Sublime Text 2\DLLs;E:\Applications\Sublime Text 2\lib;E:\Applications\Sublime Text 2\lib\plat-win;E:\Applications\Sublime Text 2\lib\lib-tk;E:\Applications\Sublime Text 2
Py_GetPythonHome(): E:\Applications\Sublime Text 2
catalogue loaded
found 11 files for base name Default.sublime-keymap
found 1 files for base name Default.sublime-mousemap
found 10 files for base name Main.sublime-menu
Reloading plugin C:\Users\lt\AppData\Roaming\Sublime Text 2\Packages\AdvancedNewFile\AdvancedNewFile.py
Reloading plugin C:\Users\lt\AppData\Roaming\Sublime Text 2\Packages\CSS\css_completions.py
Reloading plugin C:\Users\lt\AppData\Roaming\Sublime Text 2\Packages\CoffeeScript\CoffeeScript.py
Reloading plugin C:\Users\lt\AppData\Roaming\Sublime Text 2\Packages\Default\comment.py
Reloading plugin C:\Users\lt\AppData\Roaming\Sublime Text 2\Packages\Default\copy_path.py
Reloading plugin C:\Users\lt\AppData\Roaming\Sublime Text 2\Packages\Default\delete_word.py
Reloading plugin C:\Users\lt\AppData\Roaming\Sublime Text 2\Packages\Default\detect_indentation.py
Reloading plugin C:\Users\lt\AppData\Roaming\Sublime Text 2\Packages\Default\duplicate_line.py
Reloading plugin C:\Users\lt\AppData\Roaming\Sublime Text 2\Packages\Default\echo.py
Reloading plugin C:\Users\lt\AppData\Roaming\Sublime Text 2\Packages\Default\exec.py
Reloading plugin C:\Users\lt\AppData\Roaming\Sublime Text 2\Packages\Default\fold.py
Reloading plugin C:\Users\lt\AppData\Roaming\Sublime Text 2\Packages\Default\font.py
Reloading plugin C:\Users\lt\AppData\Roaming\Sublime Text 2\Packages\Default\goto_line.py
Reloading plugin C:\Users\lt\AppData\Roaming\Sublime Text 2\Packages\Default\indentation.py
Reloading plugin C:\Users\lt\AppData\Roaming\Sublime Text 2\Packages\Default\kill_ring.py
Reloading plugin C:\Users\lt\AppData\Roaming\Sublime Text 2\Packages\Default\mark.py
Reloading plugin C:\Users\lt\AppData\Roaming\Sublime Text 2\Packages\Default\new_templates.py
Reloading plugin C:\Users\lt\AppData\Roaming\Sublime Text 2\Packages\Default\open_file_settings.py
Reloading plugin C:\Users\lt\AppData\Roaming\Sublime Text 2\Packages\Default\open_in_browser.py
Reloading plugin C:\Users\lt\AppData\Roaming\Sublime Text 2\Packages\Default\paragraph.py
Reloading plugin C:\Users\lt\AppData\Roaming\Sublime Text 2\Packages\Default\save_on_focus_lost.py
Reloading plugin C:\Users\lt\AppData\Roaming\Sublime Text 2\Packages\Default\scroll.py
Reloading plugin C:\Users\lt\AppData\Roaming\Sublime Text 2\Packages\Default\set_unsaved_view_name.py
Reloading plugin C:\Users\lt\AppData\Roaming\Sublime Text 2\Packages\Default\side_bar.py
Reloading plugin C:\Users\lt\AppData\Roaming\Sublime Text 2\Packages\Default\sort.py
Reloading plugin C:\Users\lt\AppData\Roaming\Sublime Text 2\Packages\Default\swap_line.py
Reloading plugin C:\Users\lt\AppData\Roaming\Sublime Text 2\Packages\Default\switch_file.py
Reloading plugin C:\Users\lt\AppData\Roaming\Sublime Text 2\Packages\Default\transform.py
Reloading plugin C:\Users\lt\AppData\Roaming\Sublime Text 2\Packages\Default\transpose.py
Reloading plugin C:\Users\lt\AppData\Roaming\Sublime Text 2\Packages\Default\trim_trailing_white_space.py
Reloading plugin C:\Users\lt\AppData\Roaming\Sublime Text 2\Packages\Diff\diff.py
Reloading plugin C:\Users\lt\AppData\Roaming\Sublime Text 2\Packages\Emmet\emmet-plugin.py
Emmet: No need to update PyV8
Reloading plugin C:\Users\lt\AppData\Roaming\Sublime Text 2\Packages\HTML\encode_html_entities.py
Reloading plugin C:\Users\lt\AppData\Roaming\Sublime Text 2\Packages\HTML\html_completions.py
Reloading plugin C:\Users\lt\AppData\Roaming\Sublime Text 2\Packages\LiveStyle\livestyle.py
Reloading plugin C:\Users\lt\AppData\Roaming\Sublime Text 2\Packages\Local History\history.py
Reloading plugin C:\Users\lt\AppData\Roaming\Sublime Text 2\Packages\Package Control\Package Control.py
Reloading plugin C:\Users\lt\AppData\Roaming\Sublime Text 2\Packages\PlainTasks\PlainTasks.py
Reloading plugin C:\Users\lt\AppData\Roaming\Sublime Text 2\Packages\Prefixr\Prefixr.py
Reloading plugin C:\Users\lt\AppData\Roaming\Sublime Text 2\Packages\SublimeLinter\SublimeLinter.py
imported capp_lint
imported pep8
imported pyflakes
imported pyflakes.api
imported pyflakes.checker
imported pyflakes.messages
imported pyflakes.reporter
SublimeLinter: C loaded
SublimeLinter: CoffeeScript loaded
SublimeLinter: CSS loaded
SublimeLinter: c_cpplint loaded
SublimeLinter: Git Commit Message loaded
SublimeLinter: Ruby Haml loaded
SublimeLinter: haskell loaded
SublimeLinter: HTML loaded
SublimeLinter: Java loaded
SublimeLinter: JavaScript loaded
SublimeLinter: Lua loaded
SublimeLinter: Annotations loaded
SublimeLinter: Objective-J loaded
SublimeLinter: Perl loaded
SublimeLinter: PHP loaded
SublimeLinter: Puppet loaded
SublimeLinter: Python loaded
SublimeLinter: ruby-lint loaded
SublimeLinter: Ruby loaded
SublimeLinter: pylint loaded
SublimeLinter: XML loaded
Reloading plugin C:\Users\lt\AppData\Roaming\Sublime Text 2\Packages\TernJS\tern.py
plugin init time: 1.27569
Traceback (most recent call last):
  File ".\livestyle.py", line 367, in start_plugin
    start_server(int(settings.get('port')))
  File ".\livestyle.py", line 345, in start_server
    httpserver.listen(port, address='127.0.0.1')
  File ".\tornado\tcpserver.py", line 117, in listen
  File ".\tornado\netutil.py", line 91, in bind_sockets
  File "<string>", line 1, in bind
socket.error: 
loading bindings
loading pointer bindings
found 1 files for base name Brackets.sublime-theme
theme loaded
app ready
pre session restore time: 1.68815
startup cache, total files: 117 cache hits: 117
startup time: 1.7568 (package setup was not run)
SublimeLinter: css disabled (One of the following JavaScript engines must be installed: node.js, JavaScriptCore)
TernJS: No need to update PyV8
Syncing project empty
Starting TernJS server for empty with 1 libs and 0 files
loaded 857 snippets
Package Control: Skipping automatic upgrade, last run at 2013-08-11 10:49:43, next run at 2013-08-11 11:49:43 or after

**Comment by sergeche** [comment]
There’s an error starting Websocket server. Do you have a proxy or something running on 54000 port?

**Comment by larstid** [comment]
No proxy or anything on 54000 port

**Comment by sergeche** [comment]
Can you try to install ST3 beta and then LiveStyle into it? The problem might be in the other plugin so it’s a good idea to test LS on fresh ST installation.

PS: make sure you quit ST2 during testing

**Comment by mdennisa** [comment]
I have the same error
but in the console log I found this

Reloading plugin /Users/mdennisa/Library/Application Support/Sublime Text 2/Packages/LiveStyle/livestyle.py
Traceback (most recent call last):
  File "./sublime_plugin.py", line 62, in reload_plugin
  File "./livestyle.py", line 55, in <module>
    import lsutils.editor as eutils
  File "./lsutils/editor.py", line 77
SyntaxError: Non-ASCII character '\xe2' in file ./lsutils/editor.py on line 77, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details

I'm using:
- mac osx 10.7.5
- chrome version 28.0.1500.95
- st2 version 2.0.2 build 2221

**Comment by webuniverseio** [comment]
In ST3 I got some weird errors about encoding as well, but after re-installation of LiveStyle from Package Control (yes, it is there now) - it started working again.

**Comment by mrVilen** [comment]
I've got the same error.
Removing comments in File "./lsutils/editor.py", line 77 solved it.

**Comment by woncs** [comment]
@Vil2000 
I have same error too,and solved by your method,Thanks!

**Comment by mdennisa** [comment]
solved, thanks @Vil2000 

I have installed ST 3 also, and it works perfectly on both ST 2 and ST 3

**Comment by larstid** [comment]
I installed ST3 and LiveStyle succesfully. The Problem is the plugin_host.exe. In my ST2 folder is no plugin_host.exe and i don't know why. I don't want to work with ST 3 right now until ST3 is finished. So what can i do next?

@Vil2000 is not working for me.

**Comment by sergeche** [comment]
@larstid `plugin_host.exe` is a sub-process of ST3 and it can’t be a problem. If it works with fresh ST3 then the cause of the problem is one of your plugin in ST2. I’ll try to investigate this issue, but for now you can try to remove and install LiveStyle on ST2 to check if recent fixed solved the problem.

**Comment by sergeche** [comment]
Just pushed update, it might fix this issue.
PS: make sure your Chrome extension is updated too to at least 0.8.0.816 version. Otherwise package won’t work.

**Comment by rfrancisco87** [comment]
Hi, 

I have tried to install the livestly in my ST3 but it show me a access denied message...

"DPI scale: 1
startup, version: 3047 windows x64 channel: stable
executable: /C/Program Files/Sublime Text 3/sublime_text.exe
working dir: /C/Program Files/Sublime Text 3
packages path: /C/Users/Roberto/AppData/Roaming/Sublime Text 3/Packages
state path: /C/Users/Roberto/AppData/Roaming/Sublime Text 3/Local
hardware concurrency: 2
zip path: /C/Program Files/Sublime Text 3/Packages
zip path: /C/Users/Roberto/AppData/Roaming/Sublime Text 3/Installed Packages
found 3 files for base name Default.sublime-keymap
found 1 files for base name Default.sublime-mousemap
found 2 files for base name Main.sublime-menu
loading bindings
loading pointer bindings
found 1 files for base name Default.sublime-theme
theme loaded
app ready
wrote startup cache, added files: 3 orphaned files: 0 total files: 148 cache hits: 145
pre session restore time: 0.151948
startup time: 0.170948
first paint time: 0.171948
launching: /C/Program Files/Sublime Text 3/plugin_host.exe
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin Package Control.Package Control
loaded 837 snippets
plugins loaded
Package Control: No updated packages
ignored packages updated to: [Vintage, LiveStyle]
found 1 files for base name Default.sublime-theme
theme loaded
reloading Packages/User/Preferences.sublime-settings
found 1 files for base name Default.sublime-theme
theme loaded
Exception in thread Thread-5:
Traceback (most recent call last):
  File "X/threading.py", line 639, in _bootstrap_inner
  File "package_control.package_installer in C:\Users\Roberto\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 244, in run
  File "package_control.package_manager in C:\Users\Roberto\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 597, in install_package
PermissionError: [WinError 5] Acesso negado: 'c:\users\roberto\appdata\local\temp\tmpea3yai\working'

ignored packages updated to: [Vintage]
found 1 files for base name Default.sublime-theme
theme loaded
reloading Packages/User/Preferences.sublime-settings
found 1 files for base name Default.sublime-theme
theme loaded
ignored packages updated to: [Vintage, LiveStyle]
found 1 files for base name Default.sublime-theme
theme loaded
reloading Packages/User/Preferences.sublime-settings
found 1 files for base name Default.sublime-theme
theme loaded
Exception in thread Thread-10:
Traceback (most recent call last):
  File "X/threading.py", line 639, in _bootstrap_inner
  File "package_control.package_installer in C:\Users\Roberto\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 244, in run
  File "package_control.package_manager in C:\Users\Roberto\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 597, in install_package
PermissionError: [WinError 5] Acesso negado: 'c:\users\roberto\appdata\local\temp\tmp725d9t\working'

ignored packages updated to: [Vintage]
found 1 files for base name Default.sublime-theme
theme loaded
reloading Packages/User/Preferences.sublime-settings
found 1 files for base name Default.sublime-theme
theme loaded
"

I dont know what is happen.

**Comment by sergeche** [comment]
@rfrancisco87 it’s a Package Control issue, you should contact with @wbond regarding this.

**Comment by rfrancisco87** [comment]
@sergeche So, I solved this problem executing the st3 like windows admin. thanks anyway.

**Comment by wbond** [comment]
Yeah, that error seems to indicate something in windows was preventing Package Control from working the temp folder it created to install the package. This can be caused by incorrect permission settings on a folder, an anti-virus program locking a file, having the folder open in Windows explorer, or a number of other things.

It sounds like in the case of @rfrancisco87 it was related to permissions settings.
