### ISSUE TITLE
Crashing ST3

### ISSUE THREAD

**Issue by gregorywilliamnelson** [emmetio/livestyle-sublime-old#41]
The major issue I am having at the moment, and the reason I've uninstalled LiveStyle (until some of the issue have been ironed out), is that I am finding it is crashing my Sublime Text 3.

In particular it will crash even when Live Style is not active. When this happens is variable. For example, when I put a finishing */ on a comment block.

Also, when synched, it doesn't handle copying and pasting code around. For some reason it will pull code from all sorts of places. Potentially LiveStyle is only intended for manual entry of code? Maybe it needs a greater latency for parsing input.

At the moment, above anything else, this is a show stopper to production usage at our agency. But keen to see it moving forward.

Find a way to get people to pay you for this work. It's a valuable tool.

Cheers,
Greg

**Comment by sergeche** [comment]
I’m investigating crashes ST now, most likely it may happen due to invalid CSS.

LiveStyle works for any type of changes, including pasting code. Can you provide some examples when LiveStyle is unable to handle changes?

And also post your ST console log here when expected changes are not applied.

**Comment by dshster** [comment]
При вставке в CSS файл строчки из буфера обмена с открывающей фигурной скобкой (без закрывающей) ST3 стабильно зависает не выдавая никаких логов, то же самое при редактировании строки без закрывающей фигурной скобки. В общем что-то там не так с обработкой невалидного CSS кода.

**Comment by sergeche** [comment]
Just pushed update that might fix crashing. Please update ST plugin, then restart ST (it’s important) and check if it works for you

**Comment by dshster** [comment]
Сергей, зависания исчезли, но такое ощущение, что в какой-то момент портится DOM, если изменять валидный CSS, на невалидный и обратно. Визуально пропадают блоки к которым применяются стили. Прошу прощения, что не по-английски. Еще экспериментирую, чтобы выявить закономерность и напишу отдельный Issue.

**Comment by gregorywilliamnelson** [comment]
Ahh yes! That looks better. I was pasting pieces of CSS, it didnt seem to be specific.

But I tried doing a few cut and pastes after the update, I even pasted in some completely junk data, and it looks Good. It ignores the junk data :-)

I'll keep my console window open. It was actually very handy to pick up a couple of places where the CSS parsing was not valid.

Cheers,
Greg

**Comment by sergeche** [comment]
@dshster just pushed v0.8.2 of Chrome extension, let me know if it works better for you
