### ISSUE TITLE
Deletes existing selector

### ISSUE THREAD

**Issue by IlyaOvs** [emmetio/livestyle-sublime-old#43]
Hello, Sergey. Thanks for the great tool. I found next issue.
When I edit the existing class or id in dev tool, in css file the existing rules deleting and the new rule, what I've added, adds to the end of css file. 

Win 7 x64
Google Chrome   28.0.1500.95
Sublime text 3

**Comment by sergeche** [comment]
The LiveStyle workflow assumes that you should edit rules in editor (which is a better place to do this), not in DevTools. I’ll add rule hinting in future updates of LiveStyle so it can find a better place to insert newly created rule.
