### ISSUE TITLE
Unable to install in ST2

### ISSUE THREAD

**Issue by IoanDraghici** [emmetio/livestyle-sublime-old#46]
Unable to install using Package Control.

This is the log:

Reloading plugin C:\Users\eioadra\AppData\Roaming\Sublime Text 2\Packages\LiveStyle\livestyle.py
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 62, in reload_plugin
  File ".\livestyle.py", line 55, in <module>
    import lsutils.editor as eutils
  File ".\lsutils\editor.py", line 77
SyntaxError: Non-ASCII character '\xe2' in file .\lsutils\editor.py on line 77, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details
theme loaded

Thanks,
Ioan

**Comment by CaptainMat** [comment]
I've got the same issue. 
Add: # -_\- coding: utf-8 -_\- in top of livestyle editor.py

**Comment by IoanDraghici** [comment]
Thank you CaptainMat.
