### ISSUE TITLE
Invalid CSS structure

### ISSUE THREAD

**Issue by technobulka** [emmetio/livestyle-sublime-old#49]
Every keypress add to console "Emmet LiveStyle: Error: Invalid CSS structure".
ST2 build 2221.
Chrome 28.

**Comment by sergeche** [comment]
It means CSS you are working with is invalid and LiveStyle can’t parse it.

**Comment by technobulka** [comment]
But this happens even if CSS file is empty.

**Comment by sergeche** [comment]
This error appears only when you have unclosed curly braces. There’s only one caveat right now: LiveStyle can remember invalid CSS as a reference for comparison so it will always throw such error. If you sure your current CSS state is valid, simply switch from editor to another app and then back again: LS will take current file state as a reference

**Comment by technobulka** [comment]
Found the problem. It was in the IE-crutch.
//display: inline; change it to *display: inline; 

Thanks for the great plugin!
