### ISSUE TITLE
Livestyle Vim port

### ISSUE THREAD

**Issue by 0x-r4bbit** [emmetio/livestyle-sublime-old#5]
Hey there!

This livestyle-thingy plugin looks great and I love the video on emmet.io! I wonder, if it's planned to port the implementation to vim, or if there's anybody who wants to implement it with me.

Actually, I didn't write any Vim plugin yet, but I really would like to! And if somebody is out there who would take me by the hand, I would <3 to bring this stuff to Vim.

Any thoughts?

/pp

**Comment by sergeche** [comment]
I’ll try to implement LiveStyle for Vim a bit later. Altho I’m not Vim user/plugin developer.

**Comment by 0x-r4bbit** [comment]
So how about searching for some Vim devs who also want to have this feature for their fav editor? We could build a kinda Vim-Team that takes care of that plugin in this organization?

**Comment by sergeche** [comment]
Heh, I have a lot Vim debs who’d like to see official Emmet support in Vim, but still no pull request :)
https://github.com/emmetio/emmet/issues/124

**Comment by 0x-r4bbit** [comment]
Ah great, so what do you think about setting up a Vim-Team. You could add some members to the organization that only have access to the Vim plugin repository. I would ask these guys, if there are also interested in implementing this plugin for vim.

**Comment by 0x-r4bbit** [comment]
Argh. Closed this one accidently

**Comment by tarciozemel** [comment]
I don't know how to program to Vim, but I can be a tester. I use Linux Ubuntu 64bit.

**Comment by sergeche** [comment]
Check this out: https://github.com/mattn/livestyle-vim
It’s not official and even uses it’s own diff and patch implementation, so all issues should be addressed to plugin developer

**Comment by 0x-r4bbit** [comment]
Thanks, this looks good to me!

On Fri, Aug 9, 2013 at 11:38 AM, Sergey Chikuyonok <notifications@github.com

> wrote:
> 
> Check this out: https://github.com/mattn/livestyle-vim
> It’s not official and even uses it’s own diff and patch implementation, so
> all issues should be addressed to plugin developer
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/emmetio/livestyle-sublime/issues/5#issuecomment-22384677
> .

## 

/pp
