### ISSUE TITLE
Can't make LiveStyle working with ST2 on Win7 x64

### ISSUE THREAD

**Issue by optimix-designer** [emmetio/livestyle-sublime-old#50]
Hi Sergey,
It seems like this tool is great :)
Unfortunately I still can't make it working :( I installed LiveStyle plugin in ST2 and extension for Chrome. LiveStyle option appeared in the dev tools panel, I checked "Enable LiveStyle for current page" checkbox but any changes made in browser didn't appear in the ST2. I tried install LiveStyle plugin for ST2 manually from Github but it doesn't work too.

Could you please tell me what I'm doing wrong?
Thanks a lot!

Best regards,
Alexander

**Comment by sergeche** [comment]
Did you associated files in LiveStyle panel?

**Comment by LOQUILLO** [comment]
I see that's a problem like that I have.

**Comment by folmert** [comment]
Doesn't work for me either, same config (Win7 x64 + Chrome + Sublime Text 2).
It associates the .css file in DevTools, in LiveStyle panel, though.

**Comment by optimix-designer** [comment]
I tried to associate .css files with it but there are no .css files in the dropdown.

The funny thing that I got it working once, but changes were applied only in one direction (from browser to ST2, but not in opposite way). After I re-start both ST2 and Chrome it becomes not working again :( After that I tried to enable LiveStyle for other project but it didn't work again, and in the dropdown was only link to .css file from previous project I tested. So sad...

**Comment by sergeche** [comment]
Post your ST console log here, please

**Comment by optimix-designer** [comment]
Sure, here is it: http://www.mediafire.com/?8emzbb84mupln75

**Comment by sergeche** [comment]
I see you have LiveStyle under ignored packages so it can’t start properly. Either update your ignored packages settings or re-install LiveStyle

**Comment by LOQUILLO** [comment]
Hi folmert paste here a screenshot of Chrome with dev tolos.

**Comment by sergeche** [comment]
@LOQUILLO I already told what you have to do: simply pick editor file in LiveStyle devtools panel. I really don’t get what’s your problem.

**Comment by LOQUILLO** [comment]
hi fomert your ST2 logs it´s like mine:
Package Control: Installing 1 upgrades
ignored packages updated to: [SCSS, AdvancedNewFile, SASS Snippets, Sass, Vintage, CSS Snippets, Emmet Css Snippets, LiveStyle]
found 1 files for base name Default.sublime-theme
reloading /C/Users/Designer/AppData/Roaming/Sublime Text 2/Packages/LiveStyle/LiveStyle.sublime-settings
Emmet LiveStyle: Stopping server
Traceback (most recent call last):
  File ".\livestyle.py", line 205, in handle_settings_change
    start_server(int(settings.get('port')))
TypeError: int() argument must be a string or a number, not 'NoneType'
Unloading plugin C:\Users\Designer\AppData\Roaming\Sublime Text 2\Packages\LiveStyle\livestyle.py
Emmet LiveStyle: Stopping server

There are the error, maybe ST2 have ignored but in background and not in user config files.

**Comment by optimix-designer** [comment]
I uninstalled LS plugin from ST2 (at the 4th or 5th time) - and suddenly it started working properly :)

It's a pure magic :) Thank you for help and for plugins you created! I use your Emmet plugin every day)
