### ISSUE TITLE
Fix for windows 7 "no active editor"...

### ISSUE THREAD

**Issue by seanxe** [emmetio/livestyle-sublime-old#51]
Had the problem with "No active editor" running livestyle in ST2 and chrome on win7.

I don't have "localhost" bound as a host header due to other conflicts, but i could access the livestyle web socket by accessing "127.0.0.1:54000". 

Note - you can check if this works by visiting &lt;localhost address>:54000 and then you should see the message "LiveStyle websockets server is up and running"

Once you've found which address the web socket is running on, modify the following line:

https://github.com/emmetio/livestyle-sublime/blob/master/tornado/websocket.py#L368

from "host=self.request.host" to "host=&lt;localhost address>" (don't include the port!)

so in my case:

host="127.0.0.1"

then restart chrome / ST2 and it should all work fine!

Absolutely stunning plugin by the way.

(P.S sorry if this is the wrong place to post this!)

**Comment by sergeche** [comment]
I’ll release patches Chrome extension soon, it will connect to 127.0.0.1 instead of localhost

**Comment by sergeche** [comment]
The new Chrome package (0.8.0.816) will connect to `127.0.0.1`
