### ISSUE TITLE
unicode problems

### ISSUE THREAD

**Issue by rednosemonkey** [emmetio/livestyle-sublime-old#54]
Livestyle wasn't mapping changes, and I was getting the following error in my console.

UnicodeEncodeError: 'ascii' codec can't encode characters in position 162-166: ordinal not in range(128)

The issue was the Japanese comments (of course commented out) in my css. When removed, mapping worked. As the quickest fix, would you be able to prevent the parsing of comments?

**Comment by rednosemonkey** [comment]
slightly bigger problem...
font-family that doesn't use latin characters. Without wider unicode support I expect that livestyle won't work with many other languages as well.

**Comment by sergeche** [comment]
Can you post a sample CSS snippet with Japanese characters?

**Comment by sergeche** [comment]
Just pushed update, it might fix this issue.
PS: make sure your Chrome extension is updated too to at least 0.8.0.816 version. Otherwise package won’t work.

**Comment by rednosemonkey** [comment]
Thank you. I updated the extension, but currently can't get the mapping to work, even without the unicode. It's probably an issue my end. I'll try re-installing the sublime text package to see if that is the problem.

If you still need it, here is a sample of a typical Japanese font family set.

font-family:"ＭＳ Ｐゴシック","ヒラギノ角ゴ Pro W3", "Hiragino Kaku Gothic Pro", sans-serif;

**Comment by rednosemonkey** [comment]
I can confirm that mapping now works with unicode characters in the CSS files.

Thank you!
