### ISSUE TITLE
no reverse editing from livestyle to editor

### ISSUE THREAD

**Issue by ghost** [emmetio/livestyle-sublime-old#55]
The change I make in LiveStyle panel on chrome are not reported o Sublime Text. The live live refresh from Sublime to Chrome is working fine.
I'm still on Windows XP. Does it count ?

**Comment by sergeche** [comment]
Can you post ST console log here?

**Comment by ghost** [comment]
<console>
startup, version: 2221 windows x32 channel: stable
executable: /C/Program Files/Sublime Text 2/sublime_text.exe
working dir: /C/Program Files/WinSCP
packages path: /C/Documents and Settings/mael/Application Data/Sublime Text 2/Packages
settings path: /C/Documents and Settings/mael/Application Data/Sublime Text 2/Settings
PackageSetup not required
Py_GetProgramName(): sublime_text.exe
Py_GetExecPrefix(): C:\Program Files\Sublime Text 2
Py_GetProgramFullPath(): C:\Program Files\Sublime Text 2\sublime_text.exe
Py_GetPath(): C:\Program Files\Sublime Text 2\python26.zip;C:\Program Files\Sublime Text 2\DLLs;C:\Program Files\Sublime Text 2\lib;C:\Program Files\Sublime Text 2\lib\plat-win;C:\Program Files\Sublime Text 2\lib\lib-tk;C:\Program Files\Sublime Text 2
Py_GetPythonHome(): C:\Program Files\Sublime Text 2
catalogue loaded
found 7 files for base name Default.sublime-keymap
found 1 files for base name Default.sublime-mousemap
found 6 files for base name Main.sublime-menu
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\CSS\css_completions.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\CSSLint\asyncprocess.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\CSSLint\csslint.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\CSSLint\statusprocess.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Color Highlighter\ColorHighlighter.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Color Highlighter\colors.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\ColorPicker\sublimecp.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Default\comment.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Default\copy_path.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Default\delete_word.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Default\detect_indentation.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Default\duplicate_line.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Default\echo.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Default\exec.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Default\fold.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Default\font.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Default\goto_line.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Default\indentation.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Default\kill_ring.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Default\mark.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Default\new_templates.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Default\open_file_settings.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Default\open_in_browser.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Default\paragraph.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Default\save_on_focus_lost.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Default\scroll.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Default\set_unsaved_view_name.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Default\side_bar.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Default\sort.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Default\swap_line.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Default\switch_file.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Default\transform.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Default\transpose.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Default\trim_trailing_white_space.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Diff\diff.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\FTPSync\FTPSync.py
FTPSync > plugin async loaded
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\FTPSync__init__.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\FTPSync\ftpsyncexceptions.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\FTPSync\ftpsyncfiles.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\FTPSync\ftpsyncprogress.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\FTPSync\ftpsyncworker.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\FTPSync\ftpsyncwrapper.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\HTML\encode_html_entities.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\HTML\html_completions.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\LiveStyle\livestyle.py
PyV8: Creating new thread
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Package Control\Package Control.py
plugin init time: 0.443205
loading bindings
loading pointer bindings
found 1 files for base name Default.sublime-theme
theme loaded
app ready
pre session restore time: 1.55838
startup cache, total files: 107 cache hits: 107
startup time: 1.61031 (package setup was not run)
Emmet LiveStyle: You have the most recent PyV8 binary
loaded 1055 snippets
Package Control: Skipping automatic upgrade, last run at 2013-08-15 11:48:12, next run at 2013-08-15 12:48:12 or after
FTPSync > Found no config for {C:\Documents and Settings\mael\Local Settings\Temp\scp03078\wp-content\themes\coqueliko\style.css}
Traceback (most recent call last):
  File ".\FTPSync.py", line 2392, in check
  File ".\FTPSync.py", line 683, in fillPasswords
  File ".\FTPSync.py", line 706, in loadConfig
  File ".\genericpath.py", line 18, in exists
TypeError: coercing to Unicode: need string or buffer, NoneType found
Emmet LiveStyle: client connected
</console>

**Comment by ghost** [comment]
using FTPSync to open this file, but doesn't work on local files either

**Comment by sergeche** [comment]
Try to make a few changes in DevTools that should push updates into ST and send log again

**Comment by ghost** [comment]
startup, version: 2221 windows x32 channel: stable
executable: /C/Program Files/Sublime Text 2/sublime_text.exe
working dir: /C/Program Files/WinSCP
packages path: /C/Documents and Settings/mael/Application Data/Sublime Text 2/Packages
settings path: /C/Documents and Settings/mael/Application Data/Sublime Text 2/Settings
PackageSetup not required
Py_GetProgramName(): sublime_text.exe
Py_GetExecPrefix(): C:\Program Files\Sublime Text 2
Py_GetProgramFullPath(): C:\Program Files\Sublime Text 2\sublime_text.exe
Py_GetPath(): C:\Program Files\Sublime Text 2\python26.zip;C:\Program Files\Sublime Text 2\DLLs;C:\Program Files\Sublime Text 2\lib;C:\Program Files\Sublime Text 2\lib\plat-win;C:\Program Files\Sublime Text 2\lib\lib-tk;C:\Program Files\Sublime Text 2
Py_GetPythonHome(): C:\Program Files\Sublime Text 2
catalogue loaded
found 7 files for base name Default.sublime-keymap
found 1 files for base name Default.sublime-mousemap
found 6 files for base name Main.sublime-menu
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\CSS\css_completions.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\CSSLint\asyncprocess.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\CSSLint\csslint.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\CSSLint\statusprocess.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Color Highlighter\ColorHighlighter.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Color Highlighter\colors.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\ColorPicker\sublimecp.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Default\comment.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Default\copy_path.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Default\delete_word.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Default\detect_indentation.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Default\duplicate_line.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Default\echo.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Default\exec.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Default\fold.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Default\font.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Default\goto_line.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Default\indentation.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Default\kill_ring.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Default\mark.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Default\new_templates.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Default\open_file_settings.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Default\open_in_browser.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Default\paragraph.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Default\save_on_focus_lost.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Default\scroll.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Default\set_unsaved_view_name.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Default\side_bar.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Default\sort.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Default\swap_line.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Default\switch_file.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Default\transform.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Default\transpose.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Default\trim_trailing_white_space.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Diff\diff.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\FTPSync\FTPSync.py
FTPSync > plugin async loaded
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\FTPSync__init__.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\FTPSync\ftpsyncexceptions.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\FTPSync\ftpsyncfiles.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\FTPSync\ftpsyncprogress.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\FTPSync\ftpsyncworker.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\FTPSync\ftpsyncwrapper.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\HTML\encode_html_entities.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\HTML\html_completions.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\LiveStyle\livestyle.py
PyV8: Creating new thread
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Package Control\Package Control.py
plugin init time: 0.443205
loading bindings
loading pointer bindings
found 1 files for base name Default.sublime-theme
theme loaded
app ready
pre session restore time: 1.55838
startup cache, total files: 107 cache hits: 107
startup time: 1.61031 (package setup was not run)
Emmet LiveStyle: You have the most recent PyV8 binary
loaded 1055 snippets
Package Control: Skipping automatic upgrade, last run at 2013-08-15 11:48:12, next run at 2013-08-15 12:48:12 or after
FTPSync > Found no config for {C:\Documents and Settings\mael\Local Settings\Temp\scp03078\wp-content\themes\coqueliko\style.css}
Traceback (most recent call last):
  File ".\FTPSync.py", line 2392, in check
  File ".\FTPSync.py", line 683, in fillPasswords
  File ".\FTPSync.py", line 706, in loadConfig
  File ".\genericpath.py", line 18, in exists
TypeError: coercing to Unicode: need string or buffer, NoneType found
Emmet LiveStyle: client connected
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 356, in run_
  File ".\livestyle.py", line 267, in run
    payload['content'] = payload.get('content', '').decode('utf-8')
  File ".\encodings\utf_8.py", line 16, in decode
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe8' in position 98: ordinal not in range(128)

**Comment by sergeche** [comment]
Looks like you’ve got Unicode in your CSS, which is similar to #54 
I’ll try to fix it today

**Comment by ghost** [comment]
Nice !

**Comment by sergeche** [comment]
Just pushed update, it might fix this issue.
PS: make sure your Chrome extension is updated too to at least 0.8.0.816 version. Otherwise package won’t work.

**Comment by ghost** [comment]
I works, although the changes appear in Sublime, but editing a css rule frome DevTools bring the cursor to the the top of the file.
here is the log : 
startup, version: 2221 windows x32 channel: stable
executable: /C/Program Files/Sublime Text 2/sublime_text.exe
working dir: /C/Program Files/WinSCP
packages path: /C/Documents and Settings/mael/Application Data/Sublime Text 2/Packages
settings path: /C/Documents and Settings/mael/Application Data/Sublime Text 2/Settings
PackageSetup not required
Py_GetProgramName(): sublime_text.exe
Py_GetExecPrefix(): C:\Program Files\Sublime Text 2
Py_GetProgramFullPath(): C:\Program Files\Sublime Text 2\sublime_text.exe
Py_GetPath(): C:\Program Files\Sublime Text 2\python26.zip;C:\Program Files\Sublime Text 2\DLLs;C:\Program Files\Sublime Text 2\lib;C:\Program Files\Sublime Text 2\lib\plat-win;C:\Program Files\Sublime Text 2\lib\lib-tk;C:\Program Files\Sublime Text 2
Py_GetPythonHome(): C:\Program Files\Sublime Text 2
catalogue loaded
found 6 files for base name Default.sublime-keymap
found 1 files for base name Default.sublime-mousemap
found 5 files for base name Main.sublime-menu
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\CSS\css_completions.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\CSSLint\asyncprocess.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\CSSLint\csslint.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\CSSLint\statusprocess.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Color Highlighter\ColorHighlighter.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Color Highlighter\colors.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\ColorPicker\sublimecp.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Default\comment.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Default\copy_path.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Default\delete_word.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Default\detect_indentation.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Default\duplicate_line.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Default\echo.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Default\exec.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Default\fold.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Default\font.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Default\goto_line.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Default\indentation.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Default\kill_ring.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Default\mark.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Default\new_templates.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Default\open_file_settings.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Default\open_in_browser.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Default\paragraph.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Default\save_on_focus_lost.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Default\scroll.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Default\set_unsaved_view_name.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Default\side_bar.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Default\sort.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Default\swap_line.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Default\switch_file.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Default\transform.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Default\transpose.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Default\trim_trailing_white_space.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Diff\diff.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\HTML\encode_html_entities.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\HTML\html_completions.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\LiveStyle\livestyle.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Package Control\Package Control.py
plugin init time: 3.62375
loading bindings
loading pointer bindings
found 1 files for base name Default.sublime-theme
theme loaded
app ready
pre session restore time: 5.65931
wrote startup cache, added files: 2 orphaned files: 3 total files: 104 cache hits: 102
startup time: 5.88541 (package setup was not run)
loaded 1055 snippets
Package Control: No updated packages

**Comment by ghost** [comment]
It won't if I edit a rule in sublime first and then in devtools.

**Comment by sergeche** [comment]
LiveStyle workflow assumes you should add new selectors in editor (since it’s a more convenient place to do this) and use DevTools to visually tweak layout.

Anyway, I’ll try to improve updates highlighting. 

Closing this issue now since unicode issue was fixed

**Comment by ghost** [comment]
You're right, the situations occurred as I was "playing" to test the behaviour. Also, I think this will often happen, when reopening a project to make some modifications.
