### ISSUE TITLE
Opening file via Goto Anything in Sublime doesn't add file into select box

### ISSUE THREAD

**Issue by kolar** [emmetio/livestyle-sublime-old#57]
1. Open project in Sublime
2. Searching file via Goto Anything
3. Open file

![2013-08-16 1 40 49](https://f.cloud.github.com/assets/471274/972095/86a0f7a8-05f3-11e3-9df1-875644e2b3c3.png)
![2013-08-16 1 41 01](https://f.cloud.github.com/assets/471274/972096/8b64f06e-05f3-11e3-8e9f-6acb4a24d947.png)
![2013-08-16 1 39 25](https://f.cloud.github.com/assets/471274/972104/9cf4bd00-05f3-11e3-9ff2-12c6becd707e.png)

**Comment by LOQUILLO** [comment]
Your need add link href="second.css" to your HTML file.

**Comment by kolar** [comment]
No, select box contains files opened in Sublime, regardless of the HTML file content

**Comment by kolar** [comment]
Thanks, it works!
