### ISSUE TITLE
Does it work with ST3?

### ISSUE THREAD

**Issue by idan** [emmetio/livestyle-sublime-old#6]

**Comment by sergeche** [comment]
Yes, it does. If you have issues, check out ST console for errors

**Comment by rafael81** [comment]
All sublime console log is fine. But it doesn't work in ST3.

> reloading plugin LiveStyle.livestyle
> loaded 837 snippets
> PyV8: Creating new thread
> reloading plugin Pretty JSON.PrettyJson
> reloading plugin ConvertToUTF8.ConvertToUTF8
> reloading plugin Package Control.Package Control
> plugins loaded
> Emmet LiveStyle: You have the most recent PyV8 binary
> Package Control: Skipping automatic upgrade, last run at 2013-08-06 17:59:31, next run at 2013-08-06 18:59:31 or after
> Emmet LiveStyle: client connected

Can you take a look ?

**Comment by sergeche** [comment]
It works, it says Websocket server is up and running and browser extension is connected. Make sure you have associated files in DevTools panel

**Comment by rafael81** [comment]
I attached screenshoot.
![image](https://f.cloud.github.com/assets/36774/916141/5daeca86-fe83-11e2-8bf9-6e9aee731bd7.png)
![image](https://f.cloud.github.com/assets/36774/916146/7949d88a-fe83-11e2-898d-43cd7a6aac42.png)

**Comment by sergeche** [comment]
Try to inspect `<body>` element and see which styles are applied to it and if other styles are overriding `background` property.

**Comment by oskarrough** [comment]
Just confirming that it is working in ST3 for me, didn't do anything special. After mapping, try editing something in dev tools and see if it appears in your local file.
