### ISSUE TITLE
No active editor found stalls devtools window

### ISSUE THREAD

**Issue by bomakalu** [emmetio/livestyle-sublime-old#62]
Was working perfectly in canary chrome ST3 
updated both and now stall the devtools and cannot find 
active editor?
I am lost this was working fine and now nothing?
any help please?

console log below!?

**Comment by bomakalu** [comment]
zip path: /Applications/Sublime Text.app/Contents/MacOS/Packages
zip path: /Users/peterhillman/Library/Application Support/Sublime Text 3/Installed Packages
found 3 files for base name Default.sublime-keymap
found 1 files for base name Default.sublime-mousemap
found 3 files for base name Main.sublime-menu
loading bindings
loading pointer bindings
found 1 files for base name Default.sublime-theme
theme loaded
app ready
wrote startup cache, added files: 5 orphaned files: 6 total files: 151 cache hits: 146
pre session restore time: 0.339853
using gpu buffer for window
using gamma: 2 (err: 6.9282)
first paint time: 1.51106
startup time: 1.65461
launching: /Applications/Sublime Text.app/Contents/MacOS/plugin_host
loaded 837 snippets
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin LiveStyle.livestyle
reloading plugin Package Control.Package Control
plugins loaded
Emmet LiveStyle: client connected
Emmet LiveStyle: message received:
'{"action":"handshake","data":{"id":"chrome","supports":["css"]}}'
Emmet LiveStyle: Sending ws message '{"action": "id", "data": {"title": "Sublime Text 3", "files": ["/Users/peterhillman/Desktop/rabbit.css", "untitled:15"], "icon": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABu0lEQVR42q2STWsTURhG3WvdCyq4CEVBAgYCM23JjEwy+cJC41gRdTIEGyELU7BNNMJQhUBBTUjSRdRI3GThRld+gbj2JwhuR
Package Control: Skipping automatic upgrade, last run at 2013-08-21 11:28:04, next run at 2013-08-21 12:28:04 or after
Emmet LiveStyle: Prepare diff
Emmet LiveStyle: Sending ws message '{"action": "updateFiles", "data": ["/Users/peterhillman/Desktop/rabbit.css", "untitled:15"]}'

**Comment by sergeche** [comment]
As far as I can see, browser successfully connected to editor. Try to restart both Chrome and Sublime Text.
Also note that LiveStyle is not tested in Canary, there might be issues. You can also try to enable “Developer mode” in Chrome Extensions page, open `background.html` of LiveStyle extension and check if there are errors in console.

**Comment by ghost** [comment]
same problem today
console log : 
startup, version: 2221 windows x32 channel: stable
executable: /C/Program Files/Sublime Text 2/sublime_text.exe
working dir: /C/Program Files/WinSCP
packages path: /C/Documents and Settings/mael/Application Data/Sublime Text 2/Packages
settings path: /C/Documents and Settings/mael/Application Data/Sublime Text 2/Settings
PackageSetup not required
Py_GetProgramName(): sublime_text.exe
Py_GetExecPrefix(): C:\Program Files\Sublime Text 2
Py_GetProgramFullPath(): C:\Program Files\Sublime Text 2\sublime_text.exe
Py_GetPath(): C:\Program Files\Sublime Text 2\python26.zip;C:\Program Files\Sublime Text 2\DLLs;C:\Program Files\Sublime Text 2\lib;C:\Program Files\Sublime Text 2\lib\plat-win;C:\Program Files\Sublime Text 2\lib\lib-tk;C:\Program Files\Sublime Text 2
Py_GetPythonHome(): C:\Program Files\Sublime Text 2
catalogue loaded
found 6 files for base name Default.sublime-keymap
found 1 files for base name Default.sublime-mousemap
found 4 files for base name Main.sublime-menu
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\CSS\css_completions.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\CSSLint\asyncprocess.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\CSSLint\csslint.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\CSSLint\statusprocess.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Color Highlighter\ColorHighlighter.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Color Highlighter\colors.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\ColorPicker\sublimecp.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Default\comment.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Default\copy_path.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Default\delete_word.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Default\detect_indentation.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Default\duplicate_line.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Default\echo.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Default\exec.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Default\fold.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Default\font.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Default\goto_line.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Default\indentation.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Default\kill_ring.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Default\mark.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Default\new_templates.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Default\open_file_settings.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Default\open_in_browser.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Default\paragraph.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Default\save_on_focus_lost.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Default\scroll.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Default\set_unsaved_view_name.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Default\side_bar.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Default\sort.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Default\swap_line.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Default\switch_file.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Default\transform.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Default\transpose.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Default\trim_trailing_white_space.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Diff\diff.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\HTML\encode_html_entities.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\HTML\html_completions.py
Reloading plugin C:\Documents and Settings\mael\Application Data\Sublime Text 2\Packages\Package Control\Package Control.py
plugin init time: 28.6467
loading bindings
loading pointer bindings
found 1 files for base name Default.sublime-theme
theme loaded
app ready
pre session restore time: 55.346
startup cache, total files: 102 cache hits: 102
startup time: 55.9787 (package setup was not run)
Package Control: No updated packages
loaded 1055 snippets

**Comment by ghost** [comment]
livestyle window : 
![image](https://f.cloud.github.com/assets/2039020/1000413/4c13d9ce-0a4a-11e3-99f2-1015c40d5056.png)

**Comment by bomakalu** [comment]
thanks for getting bsck
it works in chrome
but there has been a serious
regression in canary

on the road mode

**Comment by sergeche** [comment]
@linearis I don’t see you have LiveStyle installed in Sublime. Make sure it is installed, also check your `ignored_packages` preference, Package Control may mistakenly add LiveStyle into it

**Comment by bomakalu** [comment]
it has to be as its working in chrome but not canary
p

on the road mode

**Comment by ghost** [comment]
LiveStyle was declared as to be ignored in my preferences. Wtf ?
How can this happen ?

**Comment by sergeche** [comment]
Looks like it’s a new Package Control bug: https://github.com/wbond/sublime_package_control/issues/558

**Comment by bomakalu** [comment]
repaired and working!
reinstalled chrome
updated and
cleared the cache!
weird?
thanks

**Comment by bomakalu** [comment]
Sergey is correct
sadly this extsnsion wont play well with
canary
it slows ans tops devtools
but it works well with chrome
thanks for great work
bo

**Comment by johncrumpton** [comment]
@sergeche Thanks - for those having the same problem in Chrome go to Preferences -> Settings – User 
and remove the LiveStyle entry under "ignored_packages"

**Comment by socialblogsite** [comment]
1) There's no such option in the latest chrome.
The further down I can go after Settings - User (edit button) is setting an avatar for my user.
Under Emmet LiveStyle options ( extensions > Emmet LiveStyle > options link ) There's just a "port" field.
2) After restarting the computer I can see SublimeText icon when open. 
I guess it's not clear enough that "the editor" is an external app, and IT MUST BE OPEN at the time of opening the chrome inspector.
3) Now that I can see the editor and open files, the dropdowns show "…" and nothing else, so I CAN'T ADD EXTRA FILES.

Between SublimeText not finding lessc this issues, I guess I'll resume lerning less until all products come out of the alfa version.

**Comment by sergeche** [comment]
@socialblogsite please read carefully docs on http://livestyle.emmet.io before posting such issues
