### ISSUE TITLE
Chrome Canary Issue

### ISSUE THREAD

**Issue by wonglok** [emmetio/livestyle-sublime-old#63]
This plugin seems breaking inside Canary. It is very slow and unresponsive. I'm currently using Chrome Standard version, works amazballs. Thanks for making such awesome plugin!

**Comment by sergeche** [comment]
LiveStyle is not tested yet in Canary, looks like there are some serious changes in DevTools internals

**Comment by wonglok** [comment]
I see~ thx~!
