### ISSUE TITLE
No active editor on Mac using Chrome + Sublime 3 or Sublime 2

### ISSUE THREAD

**Issue by akanmanu** [emmetio/livestyle-sublime-old#67]
this is the console:

startup, version: 3047 osx x64 channel: stable
executable: /Applications/Sublime Text.app/Contents/MacOS/Sublime Text
working dir: /
packages path: /Users/kissme/Library/Application Support/Sublime Text 3/Packages
state path: /Users/kissme/Library/Application Support/Sublime Text 3/Local
hardware concurrency: 4
zip path: /Applications/Sublime Text.app/Contents/MacOS/Packages
zip path: /Users/kissme/Library/Application Support/Sublime Text 3/Installed Packages
found 3 files for base name Default.sublime-keymap
found 1 files for base name Default.sublime-mousemap
found 2 files for base name Main.sublime-menu
loading bindings
loading pointer bindings
found 1 files for base name Default.sublime-theme
theme loaded
app ready
wrote startup cache, added files: 3 orphaned files: 0 total files: 148 cache hits: 145
pre session restore time: 0.305695
using gamma: 1 (err: 0)
first paint time: 0.408606
startup time: 0.41416
found 1 files for base name Default.sublime-theme
theme loaded
launching: /Applications/Sublime Text.app/Contents/MacOS/plugin_host
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin Package Control.Package Control
plugins loaded
loaded 837 snippets
Package Control: Skipping automatic upgrade, last run at 2013-08-24 14:34:20, next run at 2013-08-24 15:34:20 or after

**Comment by sergeche** [comment]
I don’t see you have installed LiveStyle plugin at all.

**Comment by akanmanu** [comment]
i've tried both method, from https://sublime.wbond.net/installation#st3
but i still have the same console

**Comment by sergeche** [comment]
The https://sublime.wbond.net/installation#st3 describes how to install Package Control.
You should then install `LiveStyle` package as described here: https://sublime.wbond.net/docs/usage

**Comment by akanmanu** [comment]
![screen shot 2013-08-29 at 6 19 23 pm](https://f.cloud.github.com/assets/3577707/1050214/10c36566-10b6-11e3-9cb5-5d380194f117.png)
ok, i've reached the list of

package:control,

now what to do next? 

> package:control : install Package

**Comment by sergeche** [comment]
Run `Install Package` command then find and install `LiveStyle` package.

**Comment by akanmanu** [comment]
ого работает :+1:
