### ISSUE TITLE
[Feature] Make it work when DevTools are closed

### ISSUE THREAD

**Issue by franciscolourenco** [emmetio/livestyle-sublime-old#68]
Is Live Style supposed to work when DevTools inspector is not open?

---

**EDIT:**

This issue is a request for the implementation of functionality which allows LiveStyle to be applied to the page when editing code in Sublime even when DevTools inspector window is closed.

If LiveStyle needs to be manually activated in Chrome, perhaps a button in the tool bar could be used for convenience (like the one the LiveReload extension)

Thanks

**Comment by sdsanders** [comment]
From the [LiveStyle docs](http://livestyle.emmet.io/usage/):

> Important: you must keep DevTools opened during live edit session and for every window (in multi-view mode). You don’t have to be on LiveStyle panel all the time but DevTools must remain opened. Otherwise, incoming updates won’t be applied.

**Comment by sergeche** [comment]
LiveStyle uses Chrome DevTools API to update CSS and this API is available only when DevTools are opened: http://developer.chrome.com/extensions/devtools.html

So you should ask Google about it.

**Comment by franciscolourenco** [comment]
The weak heel of LiveStyle

**Comment by sergeche** [comment]
I don’t think so. It’s not a problem to open DevTools panel for window just once (almost the same as pushing a button).

**Comment by franciscolourenco** [comment]
The problem isn't opening, is the space is takes space on the screen. (at leas at 13inch this is an issue)
One could detach the devtools into a separate window, but then one has to manage those loose detached windows which stay in the background, and switch those detached widows back to panels again for normal use.
It's not very practical
