### ISSUE TITLE
Not working after chrome update

### ISSUE THREAD

**Issue by iaminawe** [emmetio/livestyle-sublime-old#69]
After updating to Version 29.0.1547.57 via the automatic updater within chrome, livestyle no longer seems to be working.

Can anyone else confirm this?

**Comment by scherii** [comment]
Yep, same here.

**Comment by sergeche** [comment]
Working on a fix right now

**Comment by scherii** [comment]
Thank you! If you need additional info – just ask :) 

Edit: Console output is
<code>Port: Could not establish connection. Receiving end does not exist.</code>
<code>Error in event handler: TypeError: Cannot read property 'result' of undefined</code>

**Comment by sergeche** [comment]
Just pushed v0.8.2 of Chrome extension, let me know if it works for you

**Comment by bskimball** [comment]
Still doesn't work. It was working and was great. Now the LiveStyle button is not showing in devtools.
Chrome Version 29.0.1547.62 
LiveStyle Version 0.8.2.830

**Comment by sergeche** [comment]
Try to restart Chrome. If it doesn’t help, open DevTools in detached window and open DevTools for this window (Ctrl+Shift+I) and open Console tab: it may show errors

**Comment by bskimball** [comment]
The only errors in the console are Invalid CSS properties and tokens. I have my anti-virus disabled and I'm not showing any errors in the ST console or Chrome console. I re-installed the extension in Chrome and the Package in ST2. I might try to reinstall ST and let you know if that works.

**Comment by sergeche** [comment]
These errors for your page. You should open DevTools for DevTools

**Comment by bskimball** [comment]
I see

Failed to load resource chrome-extension://diebikgmpmeppiilkaijjbdgciafajmg/emmet.js

**Comment by bskimball** [comment]
Starting LiveStyle extension devtools.js:18

**Comment by sergeche** [comment]
It should’t be the cause of problems. Can we connect via TeamViewer so I can see what’s going on?

**Comment by bskimball** [comment]
Sure if you want

**Comment by sergeche** [comment]
OK, open TeamViewer and send me your ID and password at serge.che@gmail.com

**Comment by bskimball** [comment]
For anyone else who comes accross this page with a similar issue:

I had a corrupt Chrome user profile on Windows 7
1. Uninstall Chrome
2. navigate to AppData directory
3. navigate to Local
4. delete Google directory
5. re- install Chrome
6. re-install LiveStyle

Everything works great now!

**Comment by scherii** [comment]
Just wanted to let you know that it works for me (Chrome <code>29.0.1547.65</code>)

**Comment by EhsanKia** [comment]
I'm on Chrome 30.0.1599.28, Chrome extension 0.8.2.830 and Sublime extension v2013.09.03.21.11.17.

I haven't seen LiveStyle working for almost a month now. I don't really want to reinstall my entire Chrome to fix this. Anyone has any idea how I can debug this? Turned on debug on sublime and there didn't seem to be anything strange happening there, any way to debug the Chrome extension?

**Comment by sergeche** [comment]
@EhsanKia current Canary version is 31. LiveStyle won’t work in Canary 30 because of some temporary restrictions introduced in v30

**Comment by EhsanKia** [comment]
Well Chrome 30 is beta channel, but I just tried with Canary 31 and it still doesn't seem to be working.

**Comment by sergeche** [comment]
Can you describe what exactly isn’t working? No LiveStyle panel, no active connection, no file associations..?

**Comment by EhsanKia** [comment]
Really sorry about this. After a bit of debugging, turns out it was prefixfree that was messing me up.

**Comment by iaminawe** [comment]
Can confirm that its fixed it for me - thanks again for a really super useful workflow tool

**Comment by scherii** [comment]
Yes, I've came to the same conclusion :) sorry @sergeche!
