### ISSUE TITLE
Problems with Sublime Text 3, typing in css file forces "jump down" to bottom of file

### ISSUE THREAD

**Issue by nschaden** [emmetio/livestyle-sublime-old#71]
Sublime Text 3, (3047). I was on v2013.08.26.09.50.43 of the ST bundle, and the latest Chrome extension, on the stable channel.

I occasionally had a problem where when I had LiveStyle active (DevTools open), but as I was typing in a synced css file, for some odd reason the CSS style selector I would be writing in would suddenly "drop" to the bottom of the text editor. It strictly seemed to occur when I was typing in a new selector.

For example, I'd type:
".someclass li a"

and midway through typing the someclass, boom, it's as though the selector was automatically picked up and dropped to the bottom of the file. So I'd able to keep typing but, it's like it was suddenly punted to the end.

**Comment by sergeche** [comment]
Looks like you’ve got the same error as https://github.com/emmetio/livestyle-sublime/issues/22
I’m working on a possible fix right now, you can follow that issue for updates

**Comment by sergeche** [comment]
Just pushed v0.8.2 of Chrome extension, let me know if solves this issue.
If it still “jumps”: check if you have the same editor file is associated with multiple browser files in LiveStyle panel.
