### ISSUE TITLE
Randomly deletes text in ST2

### ISSUE THREAD

**Issue by BenWoodford** [emmetio/livestyle-sublime-old#75]
I just installed Livestyle today on ST2 and love it, except for one little quirk.

I can be typing in ST2, say "border-bottom: 2px solid transparent;" and by the time I get to the r in transparent it'll revert back the line and remove it. I imagine this is a syncing issue with Chrome, but it's definitely a problem as I've had to disable it except when I'm doing tweaks before committing to git.

Any suggestions? Is there a way to turn off Chrome -> ST2 syncing and just have it unidirectional?

**Comment by sergeche** [comment]
Looks the same as #22 

Just pushed v0.8.2 of Chrome extension, let me know if solves this issue.
I’m closing this ticket for for now, follow #22 for updates
