### ISSUE TITLE
Reapply Changes from file after Page refresh

### ISSUE THREAD

**Issue by nbchip** [emmetio/livestyle-sublime-old#76]
Im not sure if it is a Bug or Default behaviour, but after i refresh page, the changes stored in associate file are not beeing pulled in chrome and applied to page.

**Comment by sergeche** [comment]
Can you enable debug mode as described [here](https://github.com/emmetio/livestyle-sublime/blob/master/messages/install.txt) and send me full ST console log after page reload?

**Comment by nbchip** [comment]
Interesting but after adding {"debug": true} everything started working fine. Even after removing debug conf.
Just for reference - Win XP , Chrome 29, ST2 - works.

Thank you.
