### ISSUE TITLE
Only working on file://

### ISSUE THREAD

**Issue by franciscolourenco** [emmetio/livestyle-sublime-old#79]
The liveStyle panel only shows up on file:// urls, any idea why?

Chrome Stable Version 29.0.1547.62

thanks

**Comment by sergeche** [comment]
The panel shows external files only.

**Comment by franciscolourenco** [comment]
Sorry I was not totally clear. The panel doesn't appear in devtools at all.

It only appears if the url in the address bar starts with file://

**Comment by sergeche** [comment]
Check your privacy settings in Chrome (like Incognito mode)

**Comment by franciscolourenco** [comment]
Permissions:
![permissions](http://imgur.com/M9gaT0b.png)

---

Example, there is no liveStyle tab:
![dribbble](http://imgur.com/tUyRZsb.png)

---

There are some errors in the background page:
![background page](http://imgur.com/Bo35R3S.png)

**Comment by sergeche** [comment]
That’s pretty weird. What’s your LiveStyle extension version in Chrome? Also, try to temporary disable all other extensions.

**Comment by franciscolourenco** [comment]
Re-installing LiveStyle extension fixed the problem.
Thanks for the help
