### ISSUE TITLE
Stopped writing in .css files in SublimText2

### ISSUE THREAD

**Issue by peter-dsgn** [emmetio/livestyle-sublime-old#80]
Congratulations for great Idea.

I love it but it stopped working with Sublime Text. 
Tried to restart Chrome, restart SublimT2, Enable/Disable LiveStyle. But nothing. 

I've done many Undo/Redo and F5... Maybe that's why it cracked.

Any ideas how to continue working with it?

**Comment by sergeche** [comment]
https://github.com/emmetio/livestyle-sublime/blob/master/messages/install.txt

**Comment by peter-dsgn** [comment]
I did 3th step (`{"debug": true}`) but I couldn't manage 2nd:
1. It is important to add _full_ console log. You can find it via
   `View > Show Console` menu item

My colleague also didn't find this on his PC Chrome

**Comment by sergeche** [comment]
It’s not for Chrome, it’s for Sublime Text

**Comment by peter-dsgn** [comment]
Messages from Console:
Emmet LiveStyle: client disconnected
Emmet LiveStyle: Prepare diff
Emmet LiveStyle: Cannot send message, client list empty
Emmet LiveStyle: Prepare diff
Emmet LiveStyle: Cannot send message, client list empty
Emmet LiveStyle: Prepare diff
Emmet LiveStyle: Cannot send message, client list empty
Emmet LiveStyle: Prepare diff
Emmet LiveStyle: Cannot send message, client list empty
Emmet LiveStyle: Cannot send message, client list empty
Emmet LiveStyle: Cannot send message, client list empty

**Comment by sergeche** [comment]
Try to re-install Chrome extension. Also, you can enable “Developer mode” in Chrome Extensions page and check out `background.html` page for errors in Console pane

**Comment by peter-dsgn** [comment]
re-install Chrome extension- Done few times
Developer mode-  enabled
Live style Chrome extension is not connected to Sublime Text at all any more.

**Comment by sergeche** [comment]
Check the background page. Also, do you use any firewall or proxy?

**Comment by sergeche** [comment]
It’s a page in extension, as described here: https://github.com/emmetio/livestyle-sublime/issues/80#issuecomment-24299478

**Comment by peter-dsgn** [comment]
No proxy or firewall on Mac.

**Comment by peter-dsgn** [comment]
Found background.html It has opened Console

**Comment by peter-dsgn** [comment]
Got editor ID 
Object {files: Array[1], icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAA…hYE+6IliK2IwFWT3sHPsL6BnLQ4kfGmsAAAAASUVORK5CYII=", id: "st2", title: "Sublime Text 2"}
 background.js:18
Worker task "diff" performed in 3ms background.js:18
CSS parsing error at line 2, char 20: Unrecognized character '‘'
html{ font-family: ‘Asap’, Arial, sans-serif; font-weight: 400; }
-------------------^ background.js:18
Worker task "diff" performed in 1ms background.js:18
CSS parsing error at line 2, char 20: Unrecognized character '‘'
html{ font-family: ‘Asap’, Arial, sans-serif; font-weight: 400; }
-------------------^ background.js:18
Worker task "diff" performed in 0ms background.js:18
CSS parsing error at line 2, char 20: Unrecognized character '‘'
html{ font-family: ‘Asap’, Arial, sans-serif; font-weight: 400; }
-------------------^ background.js:18
Worker task "diff" performed in 0ms background.js:18
CSS parsing error at line 2, char 20: Unrecognized character '‘'
html{ font-family: ‘Asap’, Arial, sans-serif; font-weight: 400; }
-------------------^ background.js:18

**Comment by sergeche** [comment]
It means your CSS is invalid

**Comment by peter-dsgn** [comment]
I'm pushed to continue with my project.  I'll be back to try again LiveStyle. Can't wait to see when it's ready. Thank you for support.
