### ISSUE TITLE
Found problem.. works now. CodeKit was in collision with LiveStyle. 

### ISSUE THREAD

**Issue by peter-dsgn** [emmetio/livestyle-sublime-old#82]
CodeKit was in collision with LiveStyle. Thanks again for help and for super extension.

**Comment by peter-dsgn** [comment]
Ups, in fact not. Only one of several .css files is working with browser. How can I force other files to work? They are all connected with local files in LiveStyle form.

**Comment by sergeche** [comment]
If there are no errors in ST console, you should ensure that updated CSS selectors are not overridden by other ones with higher specificity.

**Comment by peter-dsgn** [comment]
WORKS!!!
