### ISSUE TITLE
Css not updating

### ISSUE THREAD

**Issue by littlegreenguy** [emmetio/livestyle-sublime-old#86]
Hi, I tried to add this to the other topic of the same description but couldn't see how.. having same problems - css not updating in either direction... clipboard problem??

log: 

Unable to extract text from the clipboard, available formats: 
Unable to extract text from the clipboard, available formats: 
Emmet LiveStyle: Sending ws message '{"data": ["\\\\192.168.1.33\\wwwroot\\ingenious_west_bridge_consulting\\css\\1140.css", "\\\\192.168.1.33\\wwwroot\\ingenious_west_bridge_consulting\\css\\style.css", "untitled:20"], "action": "updateFiles"}'
Unable to extract text from the clipboard, available formats: 
Emmet LiveStyle: Prepare diff
Emmet LiveStyle: Sending ws message '{"data": ["\\\\192.168.1.33\\wwwroot\\ingenious_west_bridge_consulting\\css\\1140.css", "\\\\192.168.1.33\\wwwroot\\ingenious_west_bridge_consulting\\css\\style.css", "untitled:20", "\\\\192.168.1.33\\wwwroot\\laxfield_capital_main\\css\\responsive-mobile.css"]
Unable to extract text from the clipboard, available formats: 
Emmet LiveStyle: Prepare diff
Emmet LiveStyle: Sending ws message '{"data": ["\\\\192.168.1.33\\wwwroot\\ingenious_west_bridge_consulting\\css\\1140.css", "\\\\192.168.1.33\\wwwroot\\ingenious_west_bridge_consulting\\css\\style.css", "untitled:20", "\\\\192.168.1.33\\wwwroot\\laxfield_capital_main\\css\\responsive-mobile.css"]
Emmet LiveStyle: Sending ws message '{"data": ["\\\\192.168.1.33\\wwwroot\\ingenious_west_bridge_consulting\\css\\1140.css", "\\\\192.168.1.33\\wwwroot\\ingenious_west_bridge_consulting\\css\\style.css", "untitled:20", "\\\\192.168.1.33\\wwwroot\\laxfield_capital_main\\css\\responsive-mobile.css"]
Unable to extract text from the clipboard, available formats: 
Emmet LiveStyle: Prepare diff
Emmet LiveStyle: Sending ws message '{"data": ["\\\\192.168.1.33\\wwwroot\\ingenious_west_bridge_consulting\\css\\1140.css", "\\\\192.168.1.33\\wwwroot\\ingenious_west_bridge_consulting\\css\\style.css", "untitled:20", "\\\\192.168.1.33\\wwwroot\\laxfield_capital_main\\css\\responsive-mobile.css",
Unable to extract text from the clipboard, available formats: 
Emmet LiveStyle: Prepare diff
Emmet LiveStyle: Sending ws message '{"data": ["\\\\192.168.1.33\\wwwroot\\ingenious_west_bridge_consulting\\css\\1140.css", "\\\\192.168.1.33\\wwwroot\\ingenious_west_bridge_consulting\\css\\style.css", "untitled:20", "\\\\192.168.1.33\\wwwroot\\laxfield_capital_main\\css\\responsive-mobile.css",
Emmet LiveStyle: Sending ws message '{"data": ["\\\\192.168.1.33\\wwwroot\\ingenious_west_bridge_consulting\\css\\1140.css", "\\\\192.168.1.33\\wwwroot\\ingenious_west_bridge_consulting\\css\\style.css", "untitled:20", "\\\\192.168.1.33\\wwwroot\\laxfield_capital_main\\css\\responsive-mobile.css",
Unable to extract text from the clipboard, available formats: 
Emmet LiveStyle: Prepare diff
Emmet LiveStyle: Sending ws message '{"data": ["\\\\192.168.1.33\\wwwroot\\ingenious_west_bridge_consulting\\css\\1140.css", "\\\\192.168.1.33\\wwwroot\\ingenious_west_bridge_consulting\\css\\style.css", "untitled:20", "\\\\192.168.1.33\\wwwroot\\laxfield_capital_main\\css\\responsive-mobile.css",
Emmet LiveStyle: Run diff
Emmet LiveStyle: Use connected "chrome" client for diff
Emmet LiveStyle: Sending ws message '{"data": {"file": 78, "source1": "/_colors \n\npurple: a30360\nbg: e8e8e8\ngrey: 333333;\nmid-grey: 666;\nlight grey: 999999;\nhot pink: ec008c;\n\n\n/_fonts_//_\nfont-family: \'Open Sans\', sans-serif;\nfont-weight: 300; light\nfont-weight: 400; normal\nfont-weight: 700; bold_/\n\n
Emmet LiveStyle: message received:
'{"action":"diff","data":{"file":78,"success":false,"result":"CSS parsing error at line 68, char 1: Unterminated string\n\tsrc=\'../images/page-bg-ie.gif\',\n^"}}'
Emmet LiveStyle: Received diff sources response: {'file': 78, 'result': "CSS parsing error at line 68, char 1: Unterminated string\n\tsrc='../images/page-bg-ie.gif',\n^", 'success': False}
Emmet LiveStyle: [ws] CSS parsing error at line 68, char 1: Unterminated string
    src='../images/page-bg-ie.gif',
^
Emmet LiveStyle: Diff performed in 0.0185s
Emmet LiveStyle: Run diff
Emmet LiveStyle: Use connected "chrome" client for diff
Emmet LiveStyle: Sending ws message '{"data": {"file": 78, "source1": "/_colors \n\npurple: a30360\nbg: e8e8e8\ngrey: 333333;\nmid-grey: 666;\nlight grey: 999999;\nhot pink: ec008c;\n\n\n/_fonts_//_\nfont-family: \'Open Sans\', sans-serif;\nfont-weight: 300; light\nfont-weight: 400; normal\nfont-weight: 700; bold_/\n\n
Emmet LiveStyle: message received:
'{"action":"diff","data":{"file":78,"success":false,"result":"CSS parsing error at line 68, char 1: Unterminated string\n\tsrc=\'../images/page-bg-ie.gif\',\n^"}}'
Emmet LiveStyle: Received diff sources response: {'file': 78, 'result': "CSS parsing error at line 68, char 1: Unterminated string\n\tsrc='../images/page-bg-ie.gif',\n^", 'success': False}
Emmet LiveStyle: [ws] CSS parsing error at line 68, char 1: Unterminated string
    src='../images/page-bg-ie.gif',
^
Emmet LiveStyle: Diff performed in 0.0165s
Emmet LiveStyle: Run diff
Emmet LiveStyle: Use connected "chrome" client for diff
Emmet LiveStyle: Sending ws message '{"data": {"file": 78, "source1": "/_colors \n\npurple: a30360\nbg: e8e8e8\ngrey: 333333;\nmid-grey: 666;\nlight grey: 999999;\nhot pink: ec008c;\n\n\n/_fonts_//_\nfont-family: \'Open Sans\', sans-serif;\nfont-weight: 300; light\nfont-weight: 400; normal\nfont-weight: 700; bold_/\n\n
Emmet LiveStyle: message received:
'{"action":"diff","data":{"file":78,"success":false,"result":"CSS parsing error at line 68, char 1: Unterminated string\n\tsrc=\'../images/page-bg-ie.gif\',\n^"}}'
Emmet LiveStyle: Received diff sources response: {'file': 78, 'result': "CSS parsing error at line 68, char 1: Unterminated string\n\tsrc='../images/page-bg-ie.gif',\n^", 'success': False}
Emmet LiveStyle: [ws] CSS parsing error at line 68, char 1: Unterminated string
    src='../images/page-bg-ie.gif',
^
Emmet LiveStyle: Diff performed in 0.0145s
Emmet LiveStyle: Run diff
Emmet LiveStyle: Use connected "chrome" client for diff
Emmet LiveStyle: Sending ws message '{"data": {"file": 78, "source1": "/_colors \n\npurple: a30360\nbg: e8e8e8\ngrey: 333333;\nmid-grey: 666;\nlight grey: 999999;\nhot pink: ec008c;\n\n\n/_fonts_//_\nfont-family: \'Open Sans\', sans-serif;\nfont-weight: 300; light\nfont-weight: 400; normal\nfont-weight: 700; bold_/\n\n
Emmet LiveStyle: message received:
'{"action":"diff","data":{"file":78,"success":false,"result":"CSS parsing error at line 68, char 1: Unterminated string\n\tsrc=\'../images/page-bg-ie.gif\',\n^"}}'
Emmet LiveStyle: Received diff sources response: {'file': 78, 'result': "CSS parsing error at line 68, char 1: Unterminated string\n\tsrc='../images/page-bg-ie.gif',\n^", 'success': False}
Emmet LiveStyle: [ws] CSS parsing error at line 68, char 1: Unterminated string
    src='../images/page-bg-ie.gif',
^
Emmet LiveStyle: Diff performed in 0.0200s
Emmet LiveStyle: Run diff
Emmet LiveStyle: Use connected "chrome" client for diff
Emmet LiveStyle: Sending ws message '{"data": {"file": 78, "source1": "/_colors \n\npurple: a30360\nbg: e8e8e8\ngrey: 333333;\nmid-grey: 666;\nlight grey: 999999;\nhot pink: ec008c;\n\n\n/_fonts_//_\nfont-family: \'Open Sans\', sans-serif;\nfont-weight: 300; light\nfont-weight: 400; normal\nfont-weight: 700; bold*/\n\n
Emmet LiveStyle: message received:
'{"action":"diff","data":{"file":78,"success":false,"result":"CSS parsing error at line 68, char 1: Unterminated string\n\tsrc=\'../images/page-bg-ie.gif\',\n^"}}'
Emmet LiveStyle: Received diff sources response: {'file': 78, 'result': "CSS parsing error at line 68, char 1: Unterminated string\n\tsrc='../images/page-bg-ie.gif',\n^", 'success': False}
Emmet LiveStyle: [ws] CSS parsing error at line 68, char 1: Unterminated string
    src='../images/page-bg-ie.gif',
^
Emmet LiveStyle: Diff performed in 0.0105s
Emmet LiveStyle: message received:
'{"action":"error","data":{"message":"CSS parsing error at line 68, char 1: Unterminated string\n\tsrc=\'../images/page-bg-ie.gif\',\n^"}}'
Emmet LiveStyle: [client] CSS parsing error at line 68, char 1: Unterminated string
    src='../images/page-bg-ie.gif',
^
Emmet LiveStyle: client disconnected
Emmet LiveStyle: client connected
Emmet LiveStyle: message received:
'{"action":"handshake","data":{"id":"chrome","supports":["css"]}}'
Emmet LiveStyle: Sending ws message '{"data": {"icon": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABu0lEQVR42q2STWsTURhG3WvdCyq4CEVBAgYCM23JjEwy+cJC41gRdTIEGyELU7BNNMJQhUBBTUjSRdRI3GThRld+gbj2JwhuRFy5cZ3Ncd5LBwZCIIIXDlzmeZ9z4d458t9WoVB4XywWCcnn89i2TSaTIZvNEuRhJvtP0e7R6XT6VYJer8dkMmE0GrHf3uPxg1s8f+TR9ncZDocq63
Unable to extract text from the clipboard, available formats: 
Emmet LiveStyle: Prepare diff
Emmet LiveStyle: Sending ws message '{"data": ["\\\\192.168.1.33\\wwwroot\\ingenious_west_bridge_consulting\\css\\1140.css", "\\\\192.168.1.33\\wwwroot\\ingenious_west_bridge_consulting\\css\\style.css", "untitled:20", "\\\\192.168.1.33\\wwwroot\\laxfield_capital_main\\css\\responsive-mobile.css",
Unable to extract text from the clipboard, available formats: 
Unable to extract text from the clipboard, available formats: 
Emmet LiveStyle: Sending ws message '{"data": ["\\\\192.168.1.33\\wwwroot\\ingenious_west_bridge_consulting\\css\\1140.css", "\\\\192.168.1.33\\wwwroot\\ingenious_west_bridge_consulting\\css\\style.css", "untitled:20", "\\\\192.168.1.33\\wwwroot\\laxfield_capital_main\\css\\responsive-mobile.css",
reloading Packages/User/Fetch.sublime-settings
Unable to extract text from the clipboard, available formats: 
Writing file //192.168.1.33/wwwroot/laxfield_capital_main/css/live.css with encoding UTF-8 (atomic)
Emmet LiveStyle: Sending ws message '{"data": {"oldname": "untitled:36", "newname": "\\\\192.168.1.33\\wwwroot\\laxfield_capital_main\\css\\live.css"}, "action": "renameFile"}'
Emmet LiveStyle: message received:
'{"action":"update","data":{"browserFile":"https://chrome.google.com/webstore/static/1381848387/wall/css/webstore.css","editorFile":null,"patch":[{"path":[[".webstore-Nb-Ob-xe-gd a",1]],"action":"update","properties":[{"name":"color","value":"red","index":1}],"removed":[]}]}}'
Emmet LiveStyle: Cannot send message, client list empty
Emmet LiveStyle: Handle CSS patch request
Emmet LiveStyle: No editor file in payload, skip patching
Unable to extract text from the clipboard, available formats: 
Emmet LiveStyle: Prepare diff
Emmet LiveStyle: Sending ws message '{"data": ["\\\\192.168.1.33\\wwwroot\\ingenious_west_bridge_consulting\\css\\1140.css", "\\\\192.168.1.33\\wwwroot\\ingenious_west_bridge_consulting\\css\\style.css", "untitled:20", "\\\\192.168.1.33\\wwwroot\\laxfield_capital_main\\css\\responsive-mobile.css",
Unable to extract text from the clipboard, available formats: 
Unable to extract text from the clipboard, available formats:

**Comment by sergeche** [comment]
CSS parsing error at line 68, char 1: Unterminated string
src='../images/page-bg-ie.gif'

**Comment by littlegreenguy** [comment]
Jeez - you're quick! schoolboy error - validated css and now works great! all power to Serge, this is some SERIOUS stuff! best of luck with development

**Comment by sergeche** [comment]
Thanks!
