### ISSUE TITLE
Overwritten CSS file bug. (SASS -> 'compiled css' -> browser)

### ISSUE THREAD

**Issue by thenyel** [emmetio/livestyle-sublime-old#87]
So I'm trying to make a 1 direction binding by having LiveStyle listen to the SASS compiled CSS which is open in sublime. the workflow looks like this:
1. Sublime Opens a SASS compiled CSS
2. LiveStyle listens to the compiled CSS
3. A grunt watch is running, recompiling the CSS as SASS file is changed
4. Sublime listens to the file update and updates current workfile (where LiveStyle listens to.
   *\* this is where it breaks
5. LiveStyle finds the file was changed, but since the file was Overwritten, the link seems to be broken, and the CSS styles in the browser is lost.

**Comment by thenyel** [comment]
I feel this is more about the Chrome Plugin issue. but couldn't find the source anywhere.

**Comment by sergeche** [comment]
LiveStyle wasn’t designed for such workflow: it tracks local changes (e.g. in editor) but completely resets its state when document is changed outside. 

You should use something like LiveReload or grunt-watch for such workflow.

**Comment by thenyel** [comment]
got it! thanks!
