### ISSUE TITLE
Doesn't work on Mavericks with ST2

### ISSUE THREAD

**Issue by kloneets** [emmetio/livestyle-sublime-old#88]
Everything is loaded, chrome addon shows sublime text and sees css file, but cann not apply changes to either side. Log:

Emmet LiveStyle: Prepare diff
Emmet LiveStyle: Sending ws message '{"action": "updateFiles", "data": ["/project/style.css", "untitled:32"]}'
Emmet LiveStyle: Run diff
Emmet LiveStyle: No suitable client for diff
Emmet LiveStyle: Run diff
Emmet LiveStyle: No suitable client for diff
Emmet LiveStyle: Run diff
Emmet LiveStyle: No suitable client for diff
Writing file /project/style.css with encoding UTF-8
Writing file /project/style.css with encoding UTF-8
Emmet LiveStyle: message received:
u'{"action":"update","data":{"browserFile":"http://localhost:8888/style.css","editorFile":"/project/style.css","patch":[{"path":[["a.rules",1]],"action":"update","properties":[{"name":"background","value":"#ccc","index":7}],"removed":[]}]}}'
Emmet LiveStyle: Cannot send message, client list empty
Emmet LiveStyle: Handle CSS patch request
Emmet LiveStyle: Request patching
Emmet LiveStyle: Start patching
Emmet LiveStyle: Client: None
Emmet LiveStyle: No suitable client for patching
Emmet LiveStyle: Prepare diff
Emmet LiveStyle: Sending ws message '{"action": "updateFiles", "data": ["/project/style.css"]}'
Emmet LiveStyle: Sending ws message '{"action": "updateFiles", "data": ["/project/style.css"]}'
Emmet LiveStyle: message received:
u'{"action":"update","data":{"browserFile":"http://localhost:8888/style.css","editorFile":"/project/style.css","patch":[{"path":[["a.rules",1]],"action":"update","properties":[{"name":"top","value":"665px","index":4}],"removed":[]}]}}'
Emmet LiveStyle: Cannot send message, client list empty
Emmet LiveStyle: Handle CSS patch request
Emmet LiveStyle: Request patching
Emmet LiveStyle: Start patching
Emmet LiveStyle: Client: None
Emmet LiveStyle: No suitable client for patching
Emmet LiveStyle: Prepare diff
Emmet LiveStyle: Prepare diff
Emmet LiveStyle: Sending ws message '{"action": "updateFiles", "data": ["/project/style.css"]}'
Emmet LiveStyle: Sending ws message '{"action": "updateFiles", "data": ["/project/style.css"]}'
Emmet LiveStyle: Prepare diff
Emmet LiveStyle: Sending ws message '{"action": "updateFiles", "data": ["/project/style.css"]}'
Emmet LiveStyle: Run diff
Emmet LiveStyle: No suitable client for diff
Writing file /project/style.css with encoding UTF-8
Emmet LiveStyle: Run diff
Emmet LiveStyle: No suitable client for diff
Emmet LiveStyle: Run diff
Emmet LiveStyle: No suitable client for diff
Emmet LiveStyle: Run diff
Emmet LiveStyle: No suitable client for diff
Emmet LiveStyle: Run diff
Emmet LiveStyle: No suitable client for diff
Emmet LiveStyle: Run diff
Emmet LiveStyle: No suitable client for diff
Emmet LiveStyle: Run diff
Emmet LiveStyle: No suitable client for diff
Emmet LiveStyle: Run diff
Emmet LiveStyle: No suitable client for diff
Writing file /project/style.css with encoding UTF-8

**Comment by sergeche** [comment]
Looks like your Chrome plugin is outdated

**Comment by kloneets** [comment]
I have 0.8.2.830 plugin version. Tried to update and even reinstall, but does not work.

**Comment by sergeche** [comment]
Can you send me a full ST log?

**Comment by kloneets** [comment]
startup, version: 2221 osx x64 channel: stable
executable: /Applications/Sublime Text 2.app/Contents/MacOS/Sublime Text 2
working dir: /
packages path: /Users/koko/Library/Application Support/Sublime Text 2/Packages
settings path: /Users/koko/Library/Application Support/Sublime Text 2/Settings
PackageSetup not required
catalogue loaded
found 20 files for base name Default.sublime-keymap
found 1 files for base name Default.sublime-mousemap
found 17 files for base name Main.sublime-menu
Reloading plugin /Users/koko/Library/Application Support/Sublime Text 2/Packages/AdvancedNewFile/AdvancedNewFile.py
Reloading plugin /Users/koko/Library/Application Support/Sublime Text 2/Packages/Alignment/Alignment.py
Reloading plugin /Users/koko/Library/Application Support/Sublime Text 2/Packages/All Autocomplete/all_views_completions.py
Reloading plugin /Users/koko/Library/Application Support/Sublime Text 2/Packages/AutoFileName/autofilename.py
Reloading plugin /Users/koko/Library/Application Support/Sublime Text 2/Packages/AutoFileName/getimageinfo.py
Reloading plugin /Users/koko/Library/Application Support/Sublime Text 2/Packages/BracketHighlighter/bh_core.py
Reloading plugin /Users/koko/Library/Application Support/Sublime Text 2/Packages/BracketHighlighter/bh_plugin.py
Reloading plugin /Users/koko/Library/Application Support/Sublime Text 2/Packages/BracketHighlighter/bh_remove.py
Reloading plugin /Users/koko/Library/Application Support/Sublime Text 2/Packages/BracketHighlighter/bh_swapping.py
Reloading plugin /Users/koko/Library/Application Support/Sublime Text 2/Packages/BracketHighlighter/bh_wrapping.py
Reloading plugin /Users/koko/Library/Application Support/Sublime Text 2/Packages/BracketHighlighter/ure.py
Reloading plugin /Users/koko/Library/Application Support/Sublime Text 2/Packages/Browser Refresh/BrowserRefresh.py
Reloading plugin /Users/koko/Library/Application Support/Sublime Text 2/Packages/CSS/css_completions.py
Reloading plugin /Users/koko/Library/Application Support/Sublime Text 2/Packages/Color Highlighter/ColorHighlighter.py
Reloading plugin /Users/koko/Library/Application Support/Sublime Text 2/Packages/Color Highlighter/colors.py
Reloading plugin /Users/koko/Library/Application Support/Sublime Text 2/Packages/Default/comment.py
Reloading plugin /Users/koko/Library/Application Support/Sublime Text 2/Packages/Default/copy_path.py
Reloading plugin /Users/koko/Library/Application Support/Sublime Text 2/Packages/Default/delete_word.py
Reloading plugin /Users/koko/Library/Application Support/Sublime Text 2/Packages/Default/detect_indentation.py
Reloading plugin /Users/koko/Library/Application Support/Sublime Text 2/Packages/Default/duplicate_line.py
Reloading plugin /Users/koko/Library/Application Support/Sublime Text 2/Packages/Default/echo.py
Reloading plugin /Users/koko/Library/Application Support/Sublime Text 2/Packages/Default/exec.py
Reloading plugin /Users/koko/Library/Application Support/Sublime Text 2/Packages/Default/fold.py
Reloading plugin /Users/koko/Library/Application Support/Sublime Text 2/Packages/Default/font.py
Reloading plugin /Users/koko/Library/Application Support/Sublime Text 2/Packages/Default/goto_line.py
Reloading plugin /Users/koko/Library/Application Support/Sublime Text 2/Packages/Default/indentation.py
Reloading plugin /Users/koko/Library/Application Support/Sublime Text 2/Packages/Default/kill_ring.py
Reloading plugin /Users/koko/Library/Application Support/Sublime Text 2/Packages/Default/mark.py
Reloading plugin /Users/koko/Library/Application Support/Sublime Text 2/Packages/Default/new_templates.py
Reloading plugin /Users/koko/Library/Application Support/Sublime Text 2/Packages/Default/open_file_settings.py
Reloading plugin /Users/koko/Library/Application Support/Sublime Text 2/Packages/Default/open_in_browser.py
Reloading plugin /Users/koko/Library/Application Support/Sublime Text 2/Packages/Default/paragraph.py
Reloading plugin /Users/koko/Library/Application Support/Sublime Text 2/Packages/Default/save_on_focus_lost.py
Reloading plugin /Users/koko/Library/Application Support/Sublime Text 2/Packages/Default/scroll.py
Reloading plugin /Users/koko/Library/Application Support/Sublime Text 2/Packages/Default/set_unsaved_view_name.py
Reloading plugin /Users/koko/Library/Application Support/Sublime Text 2/Packages/Default/side_bar.py
Reloading plugin /Users/koko/Library/Application Support/Sublime Text 2/Packages/Default/sort.py
Reloading plugin /Users/koko/Library/Application Support/Sublime Text 2/Packages/Default/swap_line.py
Reloading plugin /Users/koko/Library/Application Support/Sublime Text 2/Packages/Default/switch_file.py
Reloading plugin /Users/koko/Library/Application Support/Sublime Text 2/Packages/Default/transform.py
Reloading plugin /Users/koko/Library/Application Support/Sublime Text 2/Packages/Default/transpose.py
Reloading plugin /Users/koko/Library/Application Support/Sublime Text 2/Packages/Default/trim_trailing_white_space.py
Reloading plugin /Users/koko/Library/Application Support/Sublime Text 2/Packages/Diff/diff.py
Reloading plugin /Users/koko/Library/Application Support/Sublime Text 2/Packages/Emmet/emmet-plugin.py
Emmet: No need to update PyV8
Reloading plugin /Users/koko/Library/Application Support/Sublime Text 2/Packages/Grunt/main.py
Reloading plugin /Users/koko/Library/Application Support/Sublime Text 2/Packages/HTML/encode_html_entities.py
Reloading plugin /Users/koko/Library/Application Support/Sublime Text 2/Packages/HTML/html_completions.py
Reloading plugin /Users/koko/Library/Application Support/Sublime Text 2/Packages/LaTeX Word Count/WordCount.py
Reloading plugin /Users/koko/Library/Application Support/Sublime Text 2/Packages/Laravel 4 Artisan/Laravel 4 Artisan.py
Reloading plugin /Users/koko/Library/Application Support/Sublime Text 2/Packages/LiveStyle/livestyle.py
Reloading plugin /Users/koko/Library/Application Support/Sublime Text 2/Packages/Package Control/Package Control.py
Reloading plugin /Users/koko/Library/Application Support/Sublime Text 2/Packages/Prefixr/Prefixr.py
Reloading plugin /Users/koko/Library/Application Support/Sublime Text 2/Packages/SFTP/SFTP.py
Reloading plugin /Users/koko/Library/Application Support/Sublime Text 2/Packages/SideBarEnhancements/SideBar.py
Reloading plugin /Users/koko/Library/Application Support/Sublime Text 2/Packages/SideBarEnhancements/StatusBarFileSize.py
Reloading plugin /Users/koko/Library/Application Support/Sublime Text 2/Packages/SideBarEnhancements/StatusBarModifiedTime.py
Reloading plugin /Users/koko/Library/Application Support/Sublime Text 2/Packages/SublimeGit/SublimeGit.py
Reloading plugin /Users/koko/Library/Application Support/Sublime Text 2/Packages/Tag/Tag.py
Reloading plugin /Users/koko/Library/Application Support/Sublime Text 2/Packages/Tag/tag_close_tag.py
Reloading plugin /Users/koko/Library/Application Support/Sublime Text 2/Packages/Tag/tag_close_tag_on_slash.py
Reloading plugin /Users/koko/Library/Application Support/Sublime Text 2/Packages/Tag/tag_indent.py
Reloading plugin /Users/koko/Library/Application Support/Sublime Text 2/Packages/Tag/tag_insert_as_tag.py
Reloading plugin /Users/koko/Library/Application Support/Sublime Text 2/Packages/Tag/tag_lint.py
Reloading plugin /Users/koko/Library/Application Support/Sublime Text 2/Packages/Tag/tag_remove.py
Reloading plugin /Users/koko/Library/Application Support/Sublime Text 2/Packages/Tag/tag_remove_attributes.py
plugin init time: 0.491616
loading pointer bindings
loading bindings
found 1 files for base name Default.sublime-theme
theme loaded
app ready
pre session restore time: 0.725296
using gamma: 2 (err: 6.9282)
Emmet LiveStyle: Prepare diff
Emmet LiveStyle: Prepare diff
wrote startup cache, added files: 8 orphaned files: 0 total files: 146 cache hits: 138
startup time: 0.908781 (package setup was not run)
Emmet LiveStyle: client connected
Emmet LiveStyle: Sending ws message '{"action": "updateFiles", "data": ["/project/style.css"]}'
Emmet LiveStyle: Sending ws message '{"action": "updateFiles", "data": ["/project/style.css"]}'
Emmet LiveStyle: Sending ws message '{"action": "updateFiles", "data": ["/project/style.css"]}'
Emmet LiveStyle: Sending ws message '{"action": "id", "data": {"files": ["/project/style.css"], "icon": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABu0lEQVR42q2STWsTURhG3WvdCyq4CEVBAgYCM23JjEwy+cJC41gRdTIEGyELU7BNNMJQhUBBTUjSRdRI3GThRld+gbj2JwhuRFy5cZ3Ncd5LBwZCII
Emmet LiveStyle: Sending ws message '{"action": "updateFiles", "data": ["/project/style.css"]}'
loaded 3164 snippets
Emmet LiveStyle: Sending ws message '{"action": "updateFiles", "data": []}'
Package Control: No updated packages
Emmet LiveStyle: Prepare diff
Emmet LiveStyle: Sending ws message '{"action": "updateFiles", "data": []}'
Emmet LiveStyle: Sending ws message '{"action": "updateFiles", "data": []}'
Emmet LiveStyle: Prepare diff
Emmet LiveStyle: Sending ws message '{"action": "updateFiles", "data": ["/project/style.css"]}'
Emmet LiveStyle: Sending ws message '{"action": "updateFiles", "data": []}'
Emmet LiveStyle: Sending ws message '{"action": "updateFiles", "data": []}'
Emmet LiveStyle: Prepare diff
Emmet LiveStyle: Sending ws message '{"action": "updateFiles", "data": []}'
Emmet LiveStyle: Prepare diff
Emmet LiveStyle: Sending ws message '{"action": "updateFiles", "data": ["/project/style.css"]}'
Emmet LiveStyle: Prepare diff
Emmet LiveStyle: Sending ws message '{"action": "updateFiles", "data": ["/project/style.css"]}'
Emmet LiveStyle: message received:
u'{"action":"update","data":{"browserFile":"http://localhost:8888/style.css","editorFile":"/project/style.css","patch":[{"path":[["a.rules",1]],"action":"update","properties":[{"name":"margin-left","value":"-76px","index":5}],"removed":[]}]}}'
Emmet LiveStyle: Cannot send message, client list empty
Emmet LiveStyle: Handle CSS patch request
Emmet LiveStyle: Request patching
Emmet LiveStyle: Start patching
Emmet LiveStyle: Client: None
Emmet LiveStyle: No suitable client for patching
Emmet LiveStyle: message received:
u'{"action":"update","data":{"browserFile":"http://localhost:8888/style.css","editorFile":"/project/style.css","patch":[{"path":[["a.rules",1]],"action":"update","properties":[{"name":"width","value":"150px","index":2}],"removed":[]}]}}'
Emmet LiveStyle: Cannot send message, client list empty
Emmet LiveStyle: Handle CSS patch request
Emmet LiveStyle: Request patching
Emmet LiveStyle: Start patching
Emmet LiveStyle: Client: None
Emmet LiveStyle: No suitable client for patching
Emmet LiveStyle: message received:
u'{"action":"update","data":{"browserFile":"http://localhost:8888/style.css","editorFile":"/project/style.css","patch":[{"path":[["a.rules",1]],"action":"update","properties":[{"name":"background","value":"transparent","index":7}],"removed":[]}]}}'
Emmet LiveStyle: Cannot send message, client list empty
Emmet LiveStyle: Handle CSS patch request
Emmet LiveStyle: Request patching
Emmet LiveStyle: Start patching
Emmet LiveStyle: Client: None
Emmet LiveStyle: No suitable client for patching
Emmet LiveStyle: Prepare diff
Emmet LiveStyle: Prepare diff
Emmet LiveStyle: Sending ws message '{"action": "updateFiles", "data": ["/project/style.css"]}'
Emmet LiveStyle: Sending ws message '{"action": "updateFiles", "data": ["/project/style.css"]}'
Emmet LiveStyle: Prepare diff
Emmet LiveStyle: Sending ws message '{"action": "updateFiles", "data": ["/project/style.css"]}'
Emmet LiveStyle: Run diff
Emmet LiveStyle: No suitable client for diff
Emmet LiveStyle: Run diff
Emmet LiveStyle: No suitable client for diff
Emmet LiveStyle: Run diff
Emmet LiveStyle: No suitable client for diff
Writing file /project/style.css with encoding UTF-8

**Comment by sergeche** [comment]
Yet still, there’s something wrong with Chrome extension: it should send “handshake” message when connected but it doesn’t. Do you have any proxy/vpn enabled?

**Comment by kloneets** [comment]
Repaired disk permissions and all started to work. Maybe it can help others.
