### ISSUE TITLE
No files are listed in select box.

### ISSUE THREAD

**Issue by oimou** [emmetio/livestyle-sublime-old#9]
I've tried to associate files on chrome dev tools, but no files are listed in select box.

```
Emmet LiveStyle: Prepare diff
Emmet LiveStyle: Run diff
Emmet LiveStyle: [{"path":[[".CodeMirror",1]],"action":"update","properties":[{"name":"margin","value":"10px","index":2}],"removed":[]}]
Emmet LiveStyle: message received:
{"action":"error","data":{"message":"No associated file found"}}
Emmet LiveStyle: [client] No associated file found
```

**Comment by sergeche** [comment]
You must open or create CSS files in Sublime Text

**Comment by tyssen** [comment]
I've got the same problem. Files are open in ST2 but there's nothing in the dropdown in Chrome to choose from.

**Comment by clivewalker** [comment]
I'm seeing the same thing (Windows 7, 64 bit). The dropdowns aren't populated with anything even though the files are open/edited in ST2.

OK, now working. It seemed that the the connection took a while to be recognised.

**Comment by sergeche** [comment]
@tyssen @oimou does it work for you now?

**Comment by tyssen** [comment]
Now I get _No active editor_.

**Comment by sergeche** [comment]
@tyssen can you post your ST console log here?

**Comment by tyssen** [comment]
> startup, version: 2221 osx x64 channel: stable
> executable: /Sublime Text 2
> working dir: /
> packages path: /Packages
> settings path: /Settings
> PackageSetup not required
> catalogue loaded
> found 11 files for base name Default.sublime-keymap
> found 2 files for base name Default.sublime-mousemap
> found 10 files for base name Main.sublime-menu
> Reloading plugin /Packages/AdvancedNewFile/AdvancedNewFile.py
> Reloading plugin /Packages/Alignment/Alignment.py
> Reloading plugin /Packages/CSS/css_completions.py
> Reloading plugin /Packages/Default/comment.py
> Reloading plugin /Packages/Default/copy_path.py
> Reloading plugin /Packages/Default/delete_word.py
> Reloading plugin /Packages/Default/detect_indentation.py
> Reloading plugin /Packages/Default/duplicate_line.py
> Reloading plugin /Packages/Default/echo.py
> Reloading plugin /Packages/Default/exec.py
> Reloading plugin /Packages/Default/fold.py
> Reloading plugin /Packages/Default/font.py
> Reloading plugin /Packages/Default/goto_line.py
> Reloading plugin /Packages/Default/indentation.py
> Reloading plugin /Packages/Default/kill_ring.py
> Reloading plugin /Packages/Default/mark.py
> Reloading plugin /Packages/Default/new_templates.py
> Reloading plugin /Packages/Default/open_file_settings.py
> Reloading plugin /Packages/Default/open_in_browser.py
> Reloading plugin /Packages/Default/paragraph.py
> Reloading plugin /Packages/Default/save_on_focus_lost.py
> Reloading plugin /Packages/Default/scroll.py
> Reloading plugin /Packages/Default/set_unsaved_view_name.py
> Reloading plugin /Packages/Default/side_bar.py
> Reloading plugin /Packages/Default/sort.py
> Reloading plugin /Packages/Default/swap_line.py
> Reloading plugin /Packages/Default/switch_file.py
> Reloading plugin /Packages/Default/transform.py
> Reloading plugin /Packages/Default/transpose.py
> Reloading plugin /Packages/Default/trim_trailing_white_space.py
> Reloading plugin /Packages/Diff/diff.py
> Reloading plugin /Packages/Emmet/emmet-plugin.py
> Emmet: No need to update PyV8
> Reloading plugin /Packages/ExpressionEngine Add-On Builder/EeAddOnBuilder.py
> Reloading plugin /Packages/HTML/encode_html_entities.py
> Reloading plugin /Packages/HTML/html_completions.py
> Reloading plugin /Packages/LiveReload/livereload_st2.py
> Reloading plugin /Packages/LiveStyle/livestyle.py
> Traceback (most recent call last):
>   File "./sublime_plugin.py", line 62, in reload_plugin
>   File "./livestyle.py", line 55, in <module>
>     import lsutils.editor as eutils
>   File "./lsutils/editor.py", line 77
> SyntaxError: Non-ASCII character '\xe2' in file ./lsutils/editor.py on line 77, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details
> Reloading plugin /Packages/Open Recent Files/open_recent_files.py
> Reloading plugin /Packages/Package Control/Package Control.py
> Reloading plugin /Packages/SideBarEnhancements/SideBar.py
> Reloading plugin /Packages/SideBarEnhancements/StatusBarFileSize.py
> Reloading plugin /Packages/SideBarEnhancements/StatusBarModifiedTime.py
> Reloading plugin /Packages/SublimeCodeIntel/SublimeCodeIntel.py
> plugin init time: 1.77141
> loading bindings
> loading pointer bindings
> found 1 files for base name Default.sublime-theme
> theme loaded
> app ready
> pre session restore time: 2.19597
> using gpu buffer for window
> Loading dictionary Packages/Language - English/en_GB.dic
> using gamma: 2 (err: 6.9282)
> startup cache, total files: 126 cache hits: 126
> startup time: 3.67083 (package setup was not run)
> scan: /server/assets has been seen before, skipping (using inode) previous path: /assets inode: 256990941
> Package Control: Skipping automatic upgrade, last run at 2013-08-12 20:08:52, next run at 2013-08-12 21:08:52 or after
> loaded 1489 snippets

**Comment by sergeche** [comment]
@tyssen I’ve just pushed update, it must fix this error

**Comment by tyssen** [comment]
ST2's telling me there's no packages to upgrade. Does it take a while for upgrades to register with Package Control?

**Comment by sergeche** [comment]
Yes, you have to wait for a while or simply re-install plugin

**Comment by tyssen** [comment]
All good now and it's successfully picking up stylesheets open in ST and is live updating as intended. :)
