### ISSUE TITLE
How to install if i have proxy and can't use package controle

### ISSUE THREAD

**Issue by anjum121** [emmetio/livestyle-sublime-old#90]
I have installed it at my home computer, wanted to use it in office but we have some very strict proxy :( .

is there any way i can install it manually 

Thanks 

my log if in case 

startup, version: 2221 windows x32 channel: stable
executable: /C/Program Files/Sublime Text 2/sublime_text.exe
working dir: /C/Windows/system32
packages path: /C/Users/s760926/AppData/Roaming/Sublime Text 2/Packages
settings path: /C/Users/s760926/AppData/Roaming/Sublime Text 2/Settings
package /C/Users/s760926/AppData/Roaming/Sublime Text 2/Installed Packages/Package Control.sublime-package is newer than the installed version (/C/Users/s760926/AppData/Roaming/Sublime Text 2/Pristine Packages/Package Control.sublime-package), running PackageSetup
Py_GetProgramName(): sublime_text.exe
Py_GetExecPrefix(): C:\Program Files\Sublime Text 2
Py_GetProgramFullPath(): C:\Program Files\Sublime Text 2\sublime_text.exe
Py_GetPath(): C:\Program Files\Sublime Text 2\python26.zip;C:\Program Files\Sublime Text 2\DLLs;C:\Program Files\Sublime Text 2\lib;C:\Program Files\Sublime Text 2\lib\plat-win;C:\Program Files\Sublime Text 2\lib\lib-tk;C:\Program Files\Sublime Text 2
Py_GetPythonHome(): C:\Program Files\Sublime Text 2
PackageSetup: bad zip file at C:\Users\s760926\AppData\Roaming\Sublime Text 2\Installed Packages\Package Control.sublime-package
PackageSetup returned: -1
catalogue loaded
found 6 files for base name Default.sublime-keymap
found 1 files for base name Default.sublime-mousemap
found 4 files for base name Main.sublime-menu
Reloading plugin C:\Users\s760926\AppData\Roaming\Sublime Text 2\Packages\CSS\css_completions.py
Reloading plugin C:\Users\s760926\AppData\Roaming\Sublime Text 2\Packages\Default\comment.py
Reloading plugin C:\Users\s760926\AppData\Roaming\Sublime Text 2\Packages\Default\copy_path.py
Reloading plugin C:\Users\s760926\AppData\Roaming\Sublime Text 2\Packages\Default\delete_word.py
Reloading plugin C:\Users\s760926\AppData\Roaming\Sublime Text 2\Packages\Default\detect_indentation.py
Reloading plugin C:\Users\s760926\AppData\Roaming\Sublime Text 2\Packages\Default\duplicate_line.py
Reloading plugin C:\Users\s760926\AppData\Roaming\Sublime Text 2\Packages\Default\echo.py
Reloading plugin C:\Users\s760926\AppData\Roaming\Sublime Text 2\Packages\Default\exec.py
Reloading plugin C:\Users\s760926\AppData\Roaming\Sublime Text 2\Packages\Default\fold.py
Reloading plugin C:\Users\s760926\AppData\Roaming\Sublime Text 2\Packages\Default\font.py
Reloading plugin C:\Users\s760926\AppData\Roaming\Sublime Text 2\Packages\Default\goto_line.py
Reloading plugin C:\Users\s760926\AppData\Roaming\Sublime Text 2\Packages\Default\indentation.py
Reloading plugin C:\Users\s760926\AppData\Roaming\Sublime Text 2\Packages\Default\kill_ring.py
Reloading plugin C:\Users\s760926\AppData\Roaming\Sublime Text 2\Packages\Default\mark.py
Reloading plugin C:\Users\s760926\AppData\Roaming\Sublime Text 2\Packages\Default\new_templates.py
Reloading plugin C:\Users\s760926\AppData\Roaming\Sublime Text 2\Packages\Default\open_file_settings.py
Reloading plugin C:\Users\s760926\AppData\Roaming\Sublime Text 2\Packages\Default\open_in_browser.py
Reloading plugin C:\Users\s760926\AppData\Roaming\Sublime Text 2\Packages\Default\paragraph.py
Reloading plugin C:\Users\s760926\AppData\Roaming\Sublime Text 2\Packages\Default\save_on_focus_lost.py
Reloading plugin C:\Users\s760926\AppData\Roaming\Sublime Text 2\Packages\Default\scroll.py
Reloading plugin C:\Users\s760926\AppData\Roaming\Sublime Text 2\Packages\Default\set_unsaved_view_name.py
Reloading plugin C:\Users\s760926\AppData\Roaming\Sublime Text 2\Packages\Default\side_bar.py
Reloading plugin C:\Users\s760926\AppData\Roaming\Sublime Text 2\Packages\Default\sort.py
Reloading plugin C:\Users\s760926\AppData\Roaming\Sublime Text 2\Packages\Default\swap_line.py
Reloading plugin C:\Users\s760926\AppData\Roaming\Sublime Text 2\Packages\Default\switch_file.py
Reloading plugin C:\Users\s760926\AppData\Roaming\Sublime Text 2\Packages\Default\transform.py
Reloading plugin C:\Users\s760926\AppData\Roaming\Sublime Text 2\Packages\Default\transpose.py
Reloading plugin C:\Users\s760926\AppData\Roaming\Sublime Text 2\Packages\Default\trim_trailing_white_space.py
Reloading plugin C:\Users\s760926\AppData\Roaming\Sublime Text 2\Packages\Diff\diff.py
Reloading plugin C:\Users\s760926\AppData\Roaming\Sublime Text 2\Packages\Emmet\emmet-plugin.py
PyV8: Creating new thread
Emmet: Creating thread
Emmet: Loading https://api.github.com/repos/emmetio/pyv8-binaries/contents
Reloading plugin C:\Users\s760926\AppData\Roaming\Sublime Text 2\Packages\HTML\encode_html_entities.py
Reloading plugin C:\Users\s760926\AppData\Roaming\Sublime Text 2\Packages\HTML\html_completions.py
Reloading plugin C:\Users\s760926\AppData\Roaming\Sublime Text 2\Packages\Package Control\Package Control.py
Reloading plugin C:\Users\s760926\AppData\Roaming\Sublime Text 2\Packages\pyv8-win32\PyV8.py
plugin init time: 1.02487
loading bindings
loading pointer bindings
found 1 files for base name Default.sublime-theme
theme loaded
app ready
pre session restore time: 1.40187
startup cache, total files: 104 cache hits: 104
startup time: 1.46934 (package setup was run)
loaded 837 snippets
Package Control: Skipping automatic upgrade, last run at 2013-11-25 12:34:56, next run at 2013-11-25 13:34:56 or after
emmet.pyv8loader: Unable to download packages list. URL error [Errno 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond downloading https://api.github.com/repos/emmetio/pyv8-binaries/contents.
Exception in thread Thread-213:
Traceback (most recent call last):
  File ".\threading.py", line 532, in __bootstrap_inner
  File ".\threading.py", line 736, in run
  File ".\emmet\pyv8loader.py", line 271, in run
    return self.trigger('error', exit_code=self.thread.exit_code, progress=self)
  File ".\emmet\pyv8loader.py", line 290, in trigger
    c(_args, *_kwargs)
TypeError: on_error() got an unexpected keyword argument 'progress'

**Comment by sergeche** [comment]
This issue relates to Emmet, not LiveStyle.
https://github.com/emmetio/pyv8-binaries#manual-installation
