### ISSUE TITLE
I can't choose css files in drop down menu

### ISSUE THREAD

**Issue by Gruev** [emmetio/livestyle-sublime-old#97]
What can I do to make this plugin work

![2014-01-16 02 02 03](https://f.cloud.github.com/assets/5252275/1926380/7620a36c-7e41-11e3-821f-dbbcc41b918d.png)

startup, version: 2221 osx x64 channel: stable
executable: /Applications/Sublime Text 2.app/Contents/MacOS/Sublime Text 2
working dir: /
packages path: /Users/Gruev/Library/Application Support/Sublime Text 2/Packages
settings path: /Users/Gruev/Library/Application Support/Sublime Text 2/Settings
PackageSetup not required
catalogue loaded
found 8 files for base name Default.sublime-keymap
found 1 files for base name Default.sublime-mousemap
found 7 files for base name Main.sublime-menu
Reloading plugin /Users/Gruev/Library/Application Support/Sublime Text 2/Packages/BracketHighlighter/bh_core.py
Reloading plugin /Users/Gruev/Library/Application Support/Sublime Text 2/Packages/BracketHighlighter/bh_plugin.py
Reloading plugin /Users/Gruev/Library/Application Support/Sublime Text 2/Packages/BracketHighlighter/bh_remove.py
Reloading plugin /Users/Gruev/Library/Application Support/Sublime Text 2/Packages/BracketHighlighter/bh_swapping.py
Reloading plugin /Users/Gruev/Library/Application Support/Sublime Text 2/Packages/BracketHighlighter/bh_wrapping.py
Reloading plugin /Users/Gruev/Library/Application Support/Sublime Text 2/Packages/BracketHighlighter/ure.py
Reloading plugin /Users/Gruev/Library/Application Support/Sublime Text 2/Packages/CSS/css_completions.py
Reloading plugin /Users/Gruev/Library/Application Support/Sublime Text 2/Packages/Default/comment.py
Reloading plugin /Users/Gruev/Library/Application Support/Sublime Text 2/Packages/Default/copy_path.py
Reloading plugin /Users/Gruev/Library/Application Support/Sublime Text 2/Packages/Default/delete_word.py
Reloading plugin /Users/Gruev/Library/Application Support/Sublime Text 2/Packages/Default/detect_indentation.py
Reloading plugin /Users/Gruev/Library/Application Support/Sublime Text 2/Packages/Default/duplicate_line.py
Reloading plugin /Users/Gruev/Library/Application Support/Sublime Text 2/Packages/Default/echo.py
Reloading plugin /Users/Gruev/Library/Application Support/Sublime Text 2/Packages/Default/exec.py
Reloading plugin /Users/Gruev/Library/Application Support/Sublime Text 2/Packages/Default/fold.py
Reloading plugin /Users/Gruev/Library/Application Support/Sublime Text 2/Packages/Default/font.py
Reloading plugin /Users/Gruev/Library/Application Support/Sublime Text 2/Packages/Default/goto_line.py
Reloading plugin /Users/Gruev/Library/Application Support/Sublime Text 2/Packages/Default/indentation.py
Reloading plugin /Users/Gruev/Library/Application Support/Sublime Text 2/Packages/Default/kill_ring.py
Reloading plugin /Users/Gruev/Library/Application Support/Sublime Text 2/Packages/Default/mark.py
Reloading plugin /Users/Gruev/Library/Application Support/Sublime Text 2/Packages/Default/new_templates.py
Reloading plugin /Users/Gruev/Library/Application Support/Sublime Text 2/Packages/Default/open_file_settings.py
Reloading plugin /Users/Gruev/Library/Application Support/Sublime Text 2/Packages/Default/open_in_browser.py
Reloading plugin /Users/Gruev/Library/Application Support/Sublime Text 2/Packages/Default/paragraph.py
Reloading plugin /Users/Gruev/Library/Application Support/Sublime Text 2/Packages/Default/save_on_focus_lost.py
Reloading plugin /Users/Gruev/Library/Application Support/Sublime Text 2/Packages/Default/scroll.py
Reloading plugin /Users/Gruev/Library/Application Support/Sublime Text 2/Packages/Default/set_unsaved_view_name.py
Reloading plugin /Users/Gruev/Library/Application Support/Sublime Text 2/Packages/Default/side_bar.py
Reloading plugin /Users/Gruev/Library/Application Support/Sublime Text 2/Packages/Default/sort.py
Reloading plugin /Users/Gruev/Library/Application Support/Sublime Text 2/Packages/Default/swap_line.py
Reloading plugin /Users/Gruev/Library/Application Support/Sublime Text 2/Packages/Default/switch_file.py
Reloading plugin /Users/Gruev/Library/Application Support/Sublime Text 2/Packages/Default/transform.py
Reloading plugin /Users/Gruev/Library/Application Support/Sublime Text 2/Packages/Default/transpose.py
Reloading plugin /Users/Gruev/Library/Application Support/Sublime Text 2/Packages/Default/trim_trailing_white_space.py
Reloading plugin /Users/Gruev/Library/Application Support/Sublime Text 2/Packages/Diff/diff.py
Reloading plugin /Users/Gruev/Library/Application Support/Sublime Text 2/Packages/Emmet/emmet-plugin.py
Emmet: No need to update PyV8
Reloading plugin /Users/Gruev/Library/Application Support/Sublime Text 2/Packages/HTML/encode_html_entities.py
Reloading plugin /Users/Gruev/Library/Application Support/Sublime Text 2/Packages/HTML/html_completions.py
Reloading plugin /Users/Gruev/Library/Application Support/Sublime Text 2/Packages/LESS/less_completions.py
Reloading plugin /Users/Gruev/Library/Application Support/Sublime Text 2/Packages/LiveStyle/livestyle.py
Reloading plugin /Users/Gruev/Library/Application Support/Sublime Text 2/Packages/Package Control/Package Control.py
Reloading plugin /Users/Gruev/Library/Application Support/Sublime Text 2/Packages/SFTP/SFTP.py
plugin init time: 0.221614
loading bindings
loading pointer bindings
found 1 files for base name Default.sublime-theme
theme loaded
app ready
pre session restore time: 0.372603
using gamma: 2 (err: 6.9282)
startup cache, total files: 112 cache hits: 112
startup time: 0.486087 (package setup was not run)
Emmet LiveStyle: Cannot send message, client list empty
loaded 1055 snippets
Package Control: Skipping automatic upgrade, last run at 2014-01-16 01:03:08, next run at 2014-01-16 02:03:08 or after
Emmet LiveStyle: client connected
Emmet LiveStyle: message received:
u'{"action":"handshake","data":{"id":"chrome","supports":["css"]}}'
Emmet LiveStyle: Sending ws message '{"action": "id", "data": {"files": [], "icon": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABu0lEQVR42q2STWsTURhG3WvdCyq4CEVBAgYCM23JjEwy+cJC41gRdTIEGyELU7BNNMJQhUBBTUjSRdRI3GThRld+gbj2JwhuRFy5cZ3Ncd5LBwZCIIIXDlzmeZ9z4d458t9WoVB4XywWCcnn89i2TSaTIZvNEuRhJvtP0e7R6XT6VYJer8dkM
Writing file /Users/Gruev/Desktop/1q.com.ua/1q.com.ua/layout/stylesheets/less/style.less with encoding UTF-8

help
##

**Comment by sergeche** [comment]
Did you opened any CSS file in Sublime Text?

**Comment by Gruev** [comment]
Yes. I didn't open CSS files in my sublime, but it doesn't change the situation. LiveStyle doesn't always reload page and the connected fonts don't initialize at all.

**Comment by sergeche** [comment]
LiveStyle doesn’t reload page, it updates CSS source

**Comment by Gruev** [comment]
my problem here http://youtu.be/sWHagOFSNTc

**Comment by sergeche** [comment]
I don’t quite understand the problem: you’ve changed background color a few times and LiveStyle handles these updates, no?

Also, this is not suck kind of workflow LiveStyle was designed: you should work with CSS directly, not wait until it’s compiled by third-party tool

**Comment by Gruev** [comment]
Update only happens if I click on the tab css file in sublime. Otherwise, no update occurs page.

**Comment by sergeche** [comment]
As I said, this not the workflow LiveStyle was designed for. It doesn’t use any files, it transmits changes between editor and browsers so it detects changes in opened editor file, not the physical file on disk.

PS: LESS support will be available soon

**Comment by Gruev** [comment]
thx, because another solutions not perfect - works very slow.
